--------------------------------------------------------------------------------
-- SIIP - Sistema de Información de Inversión Pública de El Salvador
-- Esquema Oracle - Módulo Programación (M-09, M-10, M-11)
-- Depende de: schema_preinversion.sql (PROYECTO, INSTITUCION, UNIDAD_EJECUTORA,
--             USUARIO, FUENTE_FINANCIAMIENTO, DEPARTAMENTO, MUNICIPIO, ETAPA_PREINVERSION)
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. CATÁLOGOS NUEVOS
--------------------------------------------------------------------------------

-- CODIGO no tiene un código corto oficial (Anexo C.5): en MACROSECTOR es el propio nombre; en
-- SECTOR_ACTIVIDAD es "<macrosector>::<sector>" para evitar colisiones entre macrosectores.
CREATE SEQUENCE MACROSECTOR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE MACROSECTOR (
    ID_MACROSECTOR      NUMBER(19)      NOT NULL,
    CODIGO              VARCHAR2(100)   NOT NULL,
    NOMBRE              VARCHAR2(150)   NOT NULL,
    CONSTRAINT PK_MACROSECTOR PRIMARY KEY (ID_MACROSECTOR),
    CONSTRAINT UK_MACROSECTOR_CODIGO UNIQUE (CODIGO)
);
COMMENT ON TABLE MACROSECTOR IS 'Clasificador DGICP de macrosectores. CU-PRE-01 Anexo C.5; CU-PRO-05, CU-PRO-06';

CREATE SEQUENCE SECTOR_ACTIVIDAD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE SECTOR_ACTIVIDAD (
    ID_SECTOR_ACTIVIDAD NUMBER(19)      NOT NULL,
    ID_MACROSECTOR      NUMBER(19)      NOT NULL,
    CODIGO              VARCHAR2(100)   NOT NULL,
    NOMBRE              VARCHAR2(150)   NOT NULL,
    CONSTRAINT PK_SECTOR_ACTIVIDAD PRIMARY KEY (ID_SECTOR_ACTIVIDAD),
    CONSTRAINT UK_SECTOR_ACTIVIDAD_CODIGO UNIQUE (CODIGO),
    CONSTRAINT FK_SECTOR_ACT_MACROSECTOR FOREIGN KEY (ID_MACROSECTOR) REFERENCES MACROSECTOR (ID_MACROSECTOR)
);
COMMENT ON TABLE SECTOR_ACTIVIDAD IS 'Clasificador DGICP de sectores de actividad, subordinado a Macrosector. CU-PRE-01 Anexo C.5; CU-PRO-06';

CREATE SEQUENCE DIMENSION_PRIORIZ_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE DIMENSION_PRIORIZACION (
    ID_DIMENSION_PRIORIZACION NUMBER(19) NOT NULL,
    NUMERO              NUMBER(1)       NOT NULL,
    NOMBRE              VARCHAR2(150)   NOT NULL,
    DESCRIPCION         VARCHAR2(1000),
    CONSTRAINT PK_DIMENSION_PRIORIZACION PRIMARY KEY (ID_DIMENSION_PRIORIZACION),
    CONSTRAINT UK_DIMENSION_PRIORIZ_NUM UNIQUE (NUMERO),
    CONSTRAINT CK_DIMENSION_PRIORIZ_NUM CHECK (NUMERO BETWEEN 1 AND 6)
);
COMMENT ON TABLE DIMENSION_PRIORIZACION IS 'Seis dimensiones de puntuacion para priorizar proyectos en el escenario. CU-PRO-08';

--------------------------------------------------------------------------------
-- 2. PRIPME - PROGRAMACIÓN PLURIANUAL DE INVERSIÓN PÚBLICA (PRO-01, 02, 07)
--------------------------------------------------------------------------------

CREATE SEQUENCE PERIODO_PROG_PRIPME_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PERIODO_PROGRAMACION_PRIPME (
    ID_PERIODO_PRIPME   NUMBER(19)      NOT NULL,
    ANIO_DESDE          NUMBER(4)       NOT NULL,
    ANIO_HASTA          NUMBER(4)       NOT NULL,
    ESTADO              VARCHAR2(20)    NOT NULL,
    FECHA_APERTURA      TIMESTAMP,
    FECHA_CIERRE        TIMESTAMP,
    CONSTRAINT PK_PERIODO_PROG_PRIPME PRIMARY KEY (ID_PERIODO_PRIPME),
    CONSTRAINT UK_PERIODO_PRIPME_RANGO UNIQUE (ANIO_DESDE, ANIO_HASTA),
    CONSTRAINT CK_PERIODO_PRIPME_ESTADO CHECK (ESTADO IN ('ABIERTO','CERRADO'))
);
COMMENT ON TABLE PERIODO_PROGRAMACION_PRIPME IS 'Periodo plurianual n a n+5 del PRIPME, con apertura/cierre. CU-PRO-07';

CREATE SEQUENCE PRIPME_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PRIPME (
    ID_PRIPME           NUMBER(19)      NOT NULL,
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    ID_PERIODO_PRIPME   NUMBER(19)      NOT NULL,
    ESTADO_REVISION_PREINVERSION VARCHAR2(20) DEFAULT 'SIN_REVISAR' NOT NULL,
    ESTADO_REVISION_INVERSION    VARCHAR2(20) DEFAULT 'SIN_REVISAR' NOT NULL,
    FECHA_ENVIO_MONITOREO TIMESTAMP,
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    FECHA_MODIFICACION  TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR2(100),
    CONSTRAINT PK_PRIPME PRIMARY KEY (ID_PRIPME),
    CONSTRAINT UK_PRIPME_INST_PERIODO UNIQUE (ID_INSTITUCION, ID_PERIODO_PRIPME),
    CONSTRAINT FK_PRIPME_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    CONSTRAINT FK_PRIPME_PERIODO FOREIGN KEY (ID_PERIODO_PRIPME) REFERENCES PERIODO_PROGRAMACION_PRIPME (ID_PERIODO_PRIPME),
    CONSTRAINT CK_PRIPME_REV_PREINV CHECK (ESTADO_REVISION_PREINVERSION IN ('REVISADO','SIN_REVISAR')),
    CONSTRAINT CK_PRIPME_REV_INV CHECK (ESTADO_REVISION_INVERSION IN ('REVISADO','SIN_REVISAR'))
);
COMMENT ON TABLE PRIPME IS 'Cabecera del PRIPME institucional para un periodo. CU-PRO-01, CU-PRO-02';

CREATE SEQUENCE CLASIFICACION_FIN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE CLASIFICACION_FINANCIAMIENTO (
    ID_CLASIFICACION_FIN NUMBER(19)     NOT NULL,
    ID_PRIPME           NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ID_ETAPA_PREINVERSION NUMBER(19),
    TIPO_CLASIFICACION  VARCHAR2(30)    NOT NULL,
    CONSTRAINT PK_CLASIFICACION_FIN PRIMARY KEY (ID_CLASIFICACION_FIN),
    CONSTRAINT FK_CLASIF_FIN_PRIPME FOREIGN KEY (ID_PRIPME) REFERENCES PRIPME (ID_PRIPME),
    CONSTRAINT FK_CLASIF_FIN_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_CLASIF_FIN_ETAPA FOREIGN KEY (ID_ETAPA_PREINVERSION) REFERENCES ETAPA_PREINVERSION (ID_ETAPA_PREINVERSION),
    CONSTRAINT CK_CLASIF_FIN_TIPO CHECK (TIPO_CLASIFICACION IN ('CON_FINANCIAMIENTO','EN_GESTION','EN_DEMANDA_FINANCIAMIENTO'))
);
COMMENT ON TABLE CLASIFICACION_FINANCIAMIENTO IS 'Clasificacion de financiamiento de una etapa del proyecto dentro del PRIPME. CU-PRO-01';

CREATE SEQUENCE FINANCIAMIENTO_PRIPME_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE FINANCIAMIENTO_PRIPME (
    ID_FINANCIAMIENTO_PRIPME NUMBER(19) NOT NULL,
    ID_CLASIFICACION_FIN NUMBER(19)     NOT NULL,
    ID_FUENTE_FINANCIAMIENTO NUMBER(19) NOT NULL,
    ID_CONVENIO         NUMBER(19),
    ANIO                NUMBER(4)       NOT NULL,
    MONTO_PROGRAMADO    NUMBER(18,2)    NOT NULL,
    CONSTRAINT PK_FINANCIAMIENTO_PRIPME PRIMARY KEY (ID_FINANCIAMIENTO_PRIPME),
    CONSTRAINT FK_FIN_PRIPME_CLASIF FOREIGN KEY (ID_CLASIFICACION_FIN) REFERENCES CLASIFICACION_FINANCIAMIENTO (ID_CLASIFICACION_FIN),
    CONSTRAINT FK_FIN_PRIPME_FUENTE FOREIGN KEY (ID_FUENTE_FINANCIAMIENTO) REFERENCES FUENTE_FINANCIAMIENTO (ID_FUENTE_FINANCIAMIENTO)
    -- ID_CONVENIO: FK pendiente hasta procesar modulo M-14 (Convenios) [SUPUESTO]
);
COMMENT ON TABLE FINANCIAMIENTO_PRIPME IS 'Detalle de fuente/convenio y monto programado por año. CU-PRO-01';

CREATE SEQUENCE OBSERVACION_PRIPME_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE OBSERVACION_PRIPME (
    ID_OBSERVACION_PRIPME NUMBER(19)    NOT NULL,
    ID_PRIPME           NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ID_AUTOR            NUMBER(19)      NOT NULL,
    TEXTO               VARCHAR2(2000)  NOT NULL,
    FECHA_OBSERVACION   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_OBSERVACION_PRIPME PRIMARY KEY (ID_OBSERVACION_PRIPME),
    CONSTRAINT FK_OBS_PRIPME_PRIPME FOREIGN KEY (ID_PRIPME) REFERENCES PRIPME (ID_PRIPME),
    CONSTRAINT FK_OBS_PRIPME_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_OBS_PRIPME_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES USUARIO (ID_USUARIO)
);
COMMENT ON TABLE OBSERVACION_PRIPME IS 'Observaciones DGI sobre la programacion de un proyecto en el PRIPME. CU-PRO-02';

-- CU-PRO-03/04/05/06: consolidados NO generan tabla propia, son vistas agregadas [SUPUESTO]
CREATE OR REPLACE VIEW VW_CONSOLIDADO_PRIPME_INSTITUCION AS
SELECT i.ID_INSTITUCION, i.NOMBRE AS INSTITUCION, fp.ANIO,
       cf.TIPO_CLASIFICACION, SUM(fp.MONTO_PROGRAMADO) AS MONTO_TOTAL
FROM FINANCIAMIENTO_PRIPME fp
JOIN CLASIFICACION_FINANCIAMIENTO cf ON cf.ID_CLASIFICACION_FIN = fp.ID_CLASIFICACION_FIN
JOIN PRIPME p ON p.ID_PRIPME = cf.ID_PRIPME
JOIN INSTITUCION i ON i.ID_INSTITUCION = p.ID_INSTITUCION
GROUP BY i.ID_INSTITUCION, i.NOMBRE, fp.ANIO, cf.TIPO_CLASIFICACION;
COMMENT ON TABLE VW_CONSOLIDADO_PRIPME_INSTITUCION IS 'CU-PRO-03 [SUPUESTO: vista, sin tabla propia]';

CREATE OR REPLACE VIEW VW_CONSOLIDADO_PRIPME_FUENTE AS
SELECT ff.ID_FUENTE_FINANCIAMIENTO, ff.NOMBRE AS FUENTE, fp.ANIO,
       cf.TIPO_CLASIFICACION, SUM(fp.MONTO_PROGRAMADO) AS MONTO_TOTAL
FROM FINANCIAMIENTO_PRIPME fp
JOIN CLASIFICACION_FINANCIAMIENTO cf ON cf.ID_CLASIFICACION_FIN = fp.ID_CLASIFICACION_FIN
JOIN FUENTE_FINANCIAMIENTO ff ON ff.ID_FUENTE_FINANCIAMIENTO = fp.ID_FUENTE_FINANCIAMIENTO
GROUP BY ff.ID_FUENTE_FINANCIAMIENTO, ff.NOMBRE, fp.ANIO, cf.TIPO_CLASIFICACION;
COMMENT ON TABLE VW_CONSOLIDADO_PRIPME_FUENTE IS 'CU-PRO-04 [SUPUESTO: vista, sin tabla propia]';

-- Nota: VW_CONSOLIDADO_PRIPME_MACROSECTOR y _SECTOR_ACTIVIDAD (CU-PRO-05/06) requieren
-- que INSTITUCION o PROYECTO tengan FK a MACROSECTOR/SECTOR_ACTIVIDAD (hoy son VARCHAR2
-- en INSTITUCION). [SUPUESTO - pendiente normalizar cuando se valide con el equipo]

--------------------------------------------------------------------------------
-- 3. ESCENARIOS DE CORTO PLAZO Y CONTRAPROPUESTA (PRO-08, 09, 10, 11)
--------------------------------------------------------------------------------

CREATE SEQUENCE ESCENARIO_CP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ESCENARIO_CORTO_PLAZO (
    ID_ESCENARIO        NUMBER(19)      NOT NULL,
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    ESTADO              VARCHAR2(30)    DEFAULT 'GENERADO' NOT NULL,
    FECHA_GENERACION    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ENVIO_REVISION TIMESTAMP,
    FECHA_VALIDACION    TIMESTAMP,
    CONSTRAINT PK_ESCENARIO_CP PRIMARY KEY (ID_ESCENARIO),
    CONSTRAINT UK_ESCENARIO_CP_INST_ANIO UNIQUE (ID_INSTITUCION, ANIO),
    CONSTRAINT FK_ESCENARIO_CP_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    CONSTRAINT CK_ESCENARIO_CP_ESTADO CHECK (ESTADO IN ('GENERADO','AJUSTADO','EN_REVISION','VALIDADO','OBSERVADO'))
);
COMMENT ON TABLE ESCENARIO_CORTO_PLAZO IS 'Escenario unico de techo institucional para el corto plazo. CU-PRO-08, CU-PRO-09';

CREATE SEQUENCE PROYECTO_ESCENARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PROYECTO_ESCENARIO (
    ID_PROYECTO_ESCENARIO NUMBER(19)    NOT NULL,
    ID_ESCENARIO        NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    MONTO_PROPUESTO      NUMBER(18,2)   NOT NULL,
    CLASIFICACION        VARCHAR2(20)   NOT NULL,
    PUNTAJE_TOTAL        NUMBER(8,2),
    ORDEN                NUMBER(6),
    CONSTRAINT PK_PROYECTO_ESCENARIO PRIMARY KEY (ID_PROYECTO_ESCENARIO),
    CONSTRAINT UK_PROYECTO_ESCENARIO UNIQUE (ID_ESCENARIO, ID_PROYECTO),
    CONSTRAINT FK_PROY_ESC_ESCENARIO FOREIGN KEY (ID_ESCENARIO) REFERENCES ESCENARIO_CORTO_PLAZO (ID_ESCENARIO),
    CONSTRAINT FK_PROY_ESC_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_PROY_ESC_CLASIF CHECK (CLASIFICACION IN ('NUEVO','NO_PROPUESTO','ARRASTRE'))
);
COMMENT ON TABLE PROYECTO_ESCENARIO IS 'Proyecto incluido en un escenario de corto plazo. CU-PRO-08, CU-PRO-09';

CREATE SEQUENCE CALIF_PROY_ESCENARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE CALIFICACION_PROYECTO_ESCENARIO (
    ID_CALIFICACION     NUMBER(19)      NOT NULL,
    ID_PROYECTO_ESCENARIO NUMBER(19)    NOT NULL,
    ID_DIMENSION_PRIORIZACION NUMBER(19) NOT NULL,
    PUNTAJE             NUMBER(8,2)     NOT NULL,
    CONSTRAINT PK_CALIF_PROY_ESCENARIO PRIMARY KEY (ID_CALIFICACION),
    CONSTRAINT UK_CALIF_PROY_ESC_DIM UNIQUE (ID_PROYECTO_ESCENARIO, ID_DIMENSION_PRIORIZACION),
    CONSTRAINT FK_CALIF_PROY_ESC FOREIGN KEY (ID_PROYECTO_ESCENARIO) REFERENCES PROYECTO_ESCENARIO (ID_PROYECTO_ESCENARIO),
    CONSTRAINT FK_CALIF_DIMENSION FOREIGN KEY (ID_DIMENSION_PRIORIZACION) REFERENCES DIMENSION_PRIORIZACION (ID_DIMENSION_PRIORIZACION)
);
COMMENT ON TABLE CALIFICACION_PROYECTO_ESCENARIO IS 'Puntaje por dimension de priorizacion para un proyecto del escenario. CU-PRO-08';

CREATE SEQUENCE FUENTE_FIN_ESCENARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE FUENTE_FINANCIAMIENTO_ESCENARIO (
    ID_FUENTE_FIN_ESCENARIO NUMBER(19)  NOT NULL,
    ID_PROYECTO_ESCENARIO NUMBER(19)    NOT NULL,
    ID_FUENTE_FINANCIAMIENTO NUMBER(19) NOT NULL,
    MONTO               NUMBER(18,2)    NOT NULL,
    CONSTRAINT PK_FUENTE_FIN_ESCENARIO PRIMARY KEY (ID_FUENTE_FIN_ESCENARIO),
    CONSTRAINT FK_FF_ESC_PROY_ESCENARIO FOREIGN KEY (ID_PROYECTO_ESCENARIO) REFERENCES PROYECTO_ESCENARIO (ID_PROYECTO_ESCENARIO),
    CONSTRAINT FK_FF_ESC_FUENTE FOREIGN KEY (ID_FUENTE_FINANCIAMIENTO) REFERENCES FUENTE_FINANCIAMIENTO (ID_FUENTE_FINANCIAMIENTO)
);
COMMENT ON TABLE FUENTE_FINANCIAMIENTO_ESCENARIO IS 'Fuente de financiamiento asociada a un proyecto dentro del escenario. CU-PRO-09';

CREATE SEQUENCE OBSERVACION_ESCENARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE OBSERVACION_ESCENARIO (
    ID_OBSERVACION_ESCENARIO NUMBER(19) NOT NULL,
    ID_ESCENARIO        NUMBER(19)      NOT NULL,
    ID_AUTOR            NUMBER(19)      NOT NULL,
    TEXTO               VARCHAR2(2000)  NOT NULL,
    FECHA_OBSERVACION   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_OBSERVACION_ESCENARIO PRIMARY KEY (ID_OBSERVACION_ESCENARIO),
    CONSTRAINT FK_OBS_ESC_ESCENARIO FOREIGN KEY (ID_ESCENARIO) REFERENCES ESCENARIO_CORTO_PLAZO (ID_ESCENARIO),
    CONSTRAINT FK_OBS_ESC_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES USUARIO (ID_USUARIO)
);
COMMENT ON TABLE OBSERVACION_ESCENARIO IS 'Retroalimentacion del Jefe/Subjefe DGI sobre el escenario. CU-PRO-09';

CREATE SEQUENCE CONTRAPROPUESTA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE CONTRAPROPUESTA_INSTITUCIONAL (
    ID_CONTRAPROPUESTA  NUMBER(19)      NOT NULL,
    ID_ESCENARIO        NUMBER(19)      NOT NULL,
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    ESTADO              VARCHAR2(30)    DEFAULT 'EN_ELABORACION' NOT NULL,
    FECHA_ELABORACION   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_APROBACION    TIMESTAMP,
    CONSTRAINT PK_CONTRAPROPUESTA PRIMARY KEY (ID_CONTRAPROPUESTA),
    CONSTRAINT FK_CONTRAPROP_ESCENARIO FOREIGN KEY (ID_ESCENARIO) REFERENCES ESCENARIO_CORTO_PLAZO (ID_ESCENARIO),
    CONSTRAINT FK_CONTRAPROP_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    CONSTRAINT CK_CONTRAPROP_ESTADO CHECK (ESTADO IN ('EN_ELABORACION','EN_REVISION_DGI','APROBADA','APROBADA_CON_AJUSTES'))
);
COMMENT ON TABLE CONTRAPROPUESTA_INSTITUCIONAL IS 'Contrapropuesta institucional sobre la propuesta PAIP autorizada. CU-PRO-11';

CREATE SEQUENCE COMPARATIVO_ESCENARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE COMPARATIVO_ESCENARIO (
    ID_COMPARATIVO      NUMBER(19)      NOT NULL,
    ID_CONTRAPROPUESTA  NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    TIPO_CAMBIO         VARCHAR2(20)    NOT NULL,
    CONSTRAINT PK_COMPARATIVO_ESCENARIO PRIMARY KEY (ID_COMPARATIVO),
    CONSTRAINT FK_COMPARATIVO_CONTRAPROP FOREIGN KEY (ID_CONTRAPROPUESTA) REFERENCES CONTRAPROPUESTA_INSTITUCIONAL (ID_CONTRAPROPUESTA),
    CONSTRAINT FK_COMPARATIVO_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_COMPARATIVO_TIPO CHECK (TIPO_CAMBIO IN ('NUEVO','ELIMINADO','MODIFICADO','SIN_CAMBIO'))
);
COMMENT ON TABLE COMPARATIVO_ESCENARIO IS 'Clasificacion de cambios entre escenario base y contrapropuesta. CU-PRO-09, CU-PRO-11';

CREATE SEQUENCE REGISTRO_APROB_INST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE REGISTRO_APROBACION_INSTANCIA (
    ID_REGISTRO_APROBACION NUMBER(19)   NOT NULL,
    ID_CONTRAPROPUESTA  NUMBER(19)      NOT NULL,
    INSTANCIA           VARCHAR2(30)    NOT NULL,
    RESULTADO           VARCHAR2(30)    NOT NULL,
    MONTO_APROBADO      NUMBER(18,2),
    FECHA               TIMESTAMP       NOT NULL,
    CONSTRAINT PK_REGISTRO_APROB_INST PRIMARY KEY (ID_REGISTRO_APROBACION),
    CONSTRAINT FK_REG_APROB_CONTRAPROP FOREIGN KEY (ID_CONTRAPROPUESTA) REFERENCES CONTRAPROPUESTA_INSTITUCIONAL (ID_CONTRAPROPUESTA),
    CONSTRAINT CK_REG_APROB_INSTANCIA CHECK (INSTANCIA IN ('DGICP','CONSEJO_MINISTROS','ASAMBLEA_LEGISLATIVA'))
);
COMMENT ON TABLE REGISTRO_APROBACION_INSTANCIA IS 'Resultado de aprobacion del PAIP por instancia externa. CU-PRO-11';

CREATE SEQUENCE HIST_AUTORIZ_ESCENARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE HISTORICO_AUTORIZACION_ESCENARIO (
    ID_HISTORICO_AUTORIZACION NUMBER(19) NOT NULL,
    ID_ESCENARIO        NUMBER(19)      NOT NULL,
    ETAPA_AUTORIZACION  VARCHAR2(30)    NOT NULL,
    FECHA               TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_HIST_AUTORIZ_ESCENARIO PRIMARY KEY (ID_HISTORICO_AUTORIZACION),
    CONSTRAINT FK_HIST_AUTORIZ_ESCENARIO FOREIGN KEY (ID_ESCENARIO) REFERENCES ESCENARIO_CORTO_PLAZO (ID_ESCENARIO),
    CONSTRAINT CK_HIST_AUTORIZ_ETAPA CHECK (ETAPA_AUTORIZACION IN
        ('TECHO_COMUNICADO','CONTRAPROPUESTA_INSTITUCION','TECHO_APROBADO_CM','PAIP_AUTORIZADO','PAIP_MODIFICADO'))
);
COMMENT ON TABLE HISTORICO_AUTORIZACION_ESCENARIO IS 'Historico de etapas de autorizacion de un escenario. CU-PRO-10';

--------------------------------------------------------------------------------
-- 4. PROGRAMACIÓN MENSUAL DEL PAIP (PRO-17, 18, 19, 21)
--------------------------------------------------------------------------------

CREATE SEQUENCE PERIODO_PROG_PAIP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PERIODO_PROGRAMACION_PAIP (
    ID_PERIODO_PAIP     NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    ESTADO              VARCHAR2(20)    NOT NULL,
    FECHA_APERTURA      TIMESTAMP,
    FECHA_CIERRE        TIMESTAMP,
    CONSTRAINT PK_PERIODO_PROG_PAIP PRIMARY KEY (ID_PERIODO_PAIP),
    CONSTRAINT UK_PERIODO_PAIP_ANIO UNIQUE (ANIO),
    CONSTRAINT CK_PERIODO_PAIP_ESTADO CHECK (ESTADO IN ('ABIERTO','CERRADO'))
);
COMMENT ON TABLE PERIODO_PROGRAMACION_PAIP IS 'Periodo fiscal anual de programacion del PAIP. CU-PRO-21';

CREATE SEQUENCE PROG_FIN_PAIP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PROGRAMACION_FINANCIERA_PAIP (
    ID_PROG_FIN_PAIP    NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ID_FUENTE_FINANCIAMIENTO NUMBER(19) NOT NULL,
    ID_CONVENIO         NUMBER(19),
    ANIO                NUMBER(4)       NOT NULL,
    MES                 NUMBER(2)       NOT NULL,
    MONTO_PROGRAMADO    NUMBER(18,2)    NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'REGISTRADO' NOT NULL,
    CONSTRAINT PK_PROG_FIN_PAIP PRIMARY KEY (ID_PROG_FIN_PAIP),
    CONSTRAINT FK_PROG_FIN_PAIP_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_PROG_FIN_PAIP_FUENTE FOREIGN KEY (ID_FUENTE_FINANCIAMIENTO) REFERENCES FUENTE_FINANCIAMIENTO (ID_FUENTE_FINANCIAMIENTO),
    CONSTRAINT CK_PROG_FIN_PAIP_MES CHECK (MES BETWEEN 1 AND 12)
    -- ID_CONVENIO: FK pendiente hasta procesar modulo M-14 (Convenios) [SUPUESTO]
);
COMMENT ON TABLE PROGRAMACION_FINANCIERA_PAIP IS 'Programacion mensual financiera del PAIP por proyecto/fuente. CU-PRO-17';

CREATE SEQUENCE PROVISION_FINANCIERA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PROVISION_FINANCIERA (
    ID_PROVISION_FINANCIERA NUMBER(19)  NOT NULL,
    ID_PROG_FIN_PAIP    NUMBER(19)      NOT NULL,
    MONTO_PROVISION     NUMBER(18,2)    NOT NULL,
    DOCUMENTO_RESPALDO   VARCHAR2(500),
    REVISADO_POR_SYMP    NUMBER(1)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PROVISION_FINANCIERA PRIMARY KEY (ID_PROVISION_FINANCIERA),
    CONSTRAINT FK_PROVISION_FIN_PROG FOREIGN KEY (ID_PROG_FIN_PAIP) REFERENCES PROGRAMACION_FINANCIERA_PAIP (ID_PROG_FIN_PAIP)
);
COMMENT ON TABLE PROVISION_FINANCIERA IS 'Provision financiera autorizada, con documento de respaldo. CU-PRO-17';

CREATE SEQUENCE MODIF_PRESUPUESTARIA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE MODIFICACION_PRESUPUESTARIA (
    ID_MODIFICACION_PRESUPUESTARIA NUMBER(19) NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    TIPO_MODIFICACION   VARCHAR2(20)    NOT NULL,
    ORIGEN              VARCHAR2(10)    NOT NULL,
    MONTO               NUMBER(18,2)    NOT NULL,
    FECHA               TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MODIF_PRESUPUESTARIA PRIMARY KEY (ID_MODIFICACION_PRESUPUESTARIA),
    CONSTRAINT FK_MODIF_PRESUP_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_MODIF_PRESUP_TIPO CHECK (TIPO_MODIFICACION IN ('REFUERZO','INCREMENTO','DISMINUCION')),
    CONSTRAINT CK_MODIF_PRESUP_ORIGEN CHECK (ORIGEN IN ('SAFI','MANUAL'))
);
COMMENT ON TABLE MODIFICACION_PRESUPUESTARIA IS 'Modificacion presupuestaria sobre la programacion del proyecto. CU-PRO-17';

CREATE SEQUENCE PRODUCTO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PRODUCTO (
    ID_PRODUCTO         NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    NOMBRE              VARCHAR2(250)   NOT NULL,
    PESO_RELATIVO       NUMBER(5,2)     NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_PRODUCTO_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE PRODUCTO IS 'Componente fisico (producto) del proyecto, con peso relativo. CU-PRO-18';

CREATE SEQUENCE INDICADOR_PRODUCTO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE INDICADOR_PRODUCTO (
    ID_INDICADOR_PRODUCTO NUMBER(19)    NOT NULL,
    ID_PRODUCTO         NUMBER(19)      NOT NULL,
    NOMBRE              VARCHAR2(250)   NOT NULL,
    META_GLOBAL         NUMBER(18,2)    NOT NULL,
    META_ANUAL          NUMBER(18,2)    NOT NULL,
    UNIDAD_MEDIDA       VARCHAR2(50)    NOT NULL,
    CONSTRAINT PK_INDICADOR_PRODUCTO PRIMARY KEY (ID_INDICADOR_PRODUCTO),
    CONSTRAINT FK_INDICADOR_PROD_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);
COMMENT ON TABLE INDICADOR_PRODUCTO IS 'Indicador de un producto, con meta global/anual. CU-PRO-18';

CREATE SEQUENCE PROG_FISICA_MENSUAL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PROGRAMACION_FISICA_MENSUAL (
    ID_PROG_FISICA_MENSUAL NUMBER(19)   NOT NULL,
    ID_INDICADOR_PRODUCTO NUMBER(19)    NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    MES                 NUMBER(2)       NOT NULL,
    META_PROGRAMADA      NUMBER(18,2)   NOT NULL,
    PORCENTAJE           NUMBER(5,2),
    CONSTRAINT PK_PROG_FISICA_MENSUAL PRIMARY KEY (ID_PROG_FISICA_MENSUAL),
    CONSTRAINT UK_PROG_FISICA_MENSUAL UNIQUE (ID_INDICADOR_PRODUCTO, ANIO, MES),
    CONSTRAINT FK_PROG_FIS_MENSUAL_IND FOREIGN KEY (ID_INDICADOR_PRODUCTO) REFERENCES INDICADOR_PRODUCTO (ID_INDICADOR_PRODUCTO),
    CONSTRAINT CK_PROG_FIS_MENSUAL_MES CHECK (MES BETWEEN 1 AND 12)
);
COMMENT ON TABLE PROGRAMACION_FISICA_MENSUAL IS 'Meta fisica mensualizada de un indicador (Enero-Diciembre). CU-PRO-18';

CREATE SEQUENCE DISTRIB_FIN_UBIC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE DISTRIBUCION_FIN_UBICACION (
    ID_DISTRIB_FIN_UBIC NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ID_DEPARTAMENTO     NUMBER(19)      NOT NULL,
    ID_MUNICIPIO        NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    MONTO_PROGRAMADO    NUMBER(18,2)    NOT NULL,
    MONTO_PROVISION     NUMBER(18,2),
    CONSTRAINT PK_DISTRIB_FIN_UBIC PRIMARY KEY (ID_DISTRIB_FIN_UBIC),
    CONSTRAINT FK_DISTRIB_FIN_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_DISTRIB_FIN_DEPTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO),
    CONSTRAINT FK_DISTRIB_FIN_MUNICIPIO FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_MUNICIPIO)
);
COMMENT ON TABLE DISTRIBUCION_FIN_UBICACION IS 'Distribucion financiera del proyecto por ubicacion geografica. CU-PRO-19';

CREATE SEQUENCE REVISION_TEC_PAIP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE REVISION_TECNICA_PAIP (
    ID_REVISION_TEC_PAIP NUMBER(19)     NOT NULL,
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    ID_PERIODO_PAIP     NUMBER(19)      NOT NULL,
    TIPO_REVISION       VARCHAR2(20)    NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'SIN_REVISAR' NOT NULL,
    FECHA_REVISION      TIMESTAMP,
    CONSTRAINT PK_REVISION_TEC_PAIP PRIMARY KEY (ID_REVISION_TEC_PAIP),
    CONSTRAINT UK_REVISION_TEC_PAIP UNIQUE (ID_INSTITUCION, ID_PERIODO_PAIP, TIPO_REVISION),
    CONSTRAINT FK_REV_TEC_PAIP_INST FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    CONSTRAINT FK_REV_TEC_PAIP_PERIODO FOREIGN KEY (ID_PERIODO_PAIP) REFERENCES PERIODO_PROGRAMACION_PAIP (ID_PERIODO_PAIP),
    CONSTRAINT CK_REV_TEC_PAIP_TIPO CHECK (TIPO_REVISION IN ('FINANCIERO','FISICO','GEOGRAFICO')),
    CONSTRAINT CK_REV_TEC_PAIP_ESTADO CHECK (ESTADO IN ('REVISADO','SIN_REVISAR'))
);
COMMENT ON TABLE REVISION_TECNICA_PAIP IS 'Estado de revision tecnica de la programacion del PAIP por institucion. CU-PRO-21';

--------------------------------------------------------------------------------
-- 5. MONITOREO DEL PAP (PRO-25)
--------------------------------------------------------------------------------

CREATE SEQUENCE PERIODO_PROG_PAP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PERIODO_PROGRAMACION_PAP (
    ID_PERIODO_PAP      NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    CUATRIMESTRE        NUMBER(1)       NOT NULL,
    ESTADO              VARCHAR2(20)    NOT NULL,
    FECHA_APERTURA      TIMESTAMP,
    FECHA_CIERRE        TIMESTAMP,
    CONSTRAINT PK_PERIODO_PROG_PAP PRIMARY KEY (ID_PERIODO_PAP),
    CONSTRAINT UK_PERIODO_PAP UNIQUE (ANIO, CUATRIMESTRE),
    CONSTRAINT CK_PERIODO_PAP_ESTADO CHECK (ESTADO IN ('ABIERTO','CERRADO')),
    CONSTRAINT CK_PERIODO_PAP_CUATRI CHECK (CUATRIMESTRE IN (1,2,3))
);
COMMENT ON TABLE PERIODO_PROGRAMACION_PAP IS 'Periodo cuatrimestral de programacion del PAP. CU-PRO-25';

CREATE SEQUENCE REVISION_TEC_PAP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE REVISION_TECNICA_PAP (
    ID_REVISION_TEC_PAP NUMBER(19)      NOT NULL,
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    ID_PERIODO_PAP      NUMBER(19)      NOT NULL,
    TIPO_REVISION       VARCHAR2(20)    NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'SIN_REVISAR' NOT NULL,
    FECHA_REVISION      TIMESTAMP,
    CONSTRAINT PK_REVISION_TEC_PAP PRIMARY KEY (ID_REVISION_TEC_PAP),
    CONSTRAINT UK_REVISION_TEC_PAP UNIQUE (ID_INSTITUCION, ID_PERIODO_PAP, TIPO_REVISION),
    CONSTRAINT FK_REV_TEC_PAP_INST FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    CONSTRAINT FK_REV_TEC_PAP_PERIODO FOREIGN KEY (ID_PERIODO_PAP) REFERENCES PERIODO_PROGRAMACION_PAP (ID_PERIODO_PAP),
    CONSTRAINT CK_REV_TEC_PAP_TIPO CHECK (TIPO_REVISION IN ('FINANCIERO','METAS')),
    CONSTRAINT CK_REV_TEC_PAP_ESTADO CHECK (ESTADO IN ('REVISADO','SIN_REVISAR'))
);
COMMENT ON TABLE REVISION_TECNICA_PAP IS 'Estado de revision tecnica de la programacion del PAP por institucion. CU-PRO-25';

--------------------------------------------------------------------------------
-- FIN DEL SCRIPT - Módulo Programación
--------------------------------------------------------------------------------
