--------------------------------------------------------------------------------
-- SIIP - Sistema de Información de Inversión Pública de El Salvador
-- Esquema Oracle - Módulo Convenios de Financiamiento (M-14)
-- Depende de: schema_preinversion.sql (INSTITUCION, PROYECTO)
--             schema_programacion.sql (FINANCIAMIENTO_PRIPME, PROGRAMACION_FINANCIERA_PAIP)
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. CATÁLOGOS
--------------------------------------------------------------------------------

CREATE SEQUENCE ORGANISMO_ACREEDOR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ORGANISMO_ACREEDOR (
    ID_ORGANISMO_ACREEDOR NUMBER(19)    NOT NULL,
    CODIGO              VARCHAR2(20)    NOT NULL,
    NOMBRE              VARCHAR2(250)   NOT NULL,
    ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ORGANISMO_ACREEDOR PRIMARY KEY (ID_ORGANISMO_ACREEDOR),
    CONSTRAINT UK_ORGANISMO_ACREEDOR_COD UNIQUE (CODIGO)
);
COMMENT ON TABLE ORGANISMO_ACREEDOR IS 'Catalogo de organismos acreedores (CU-PRE-17, hoja F. Recursos). CU-MPD-01';

--------------------------------------------------------------------------------
-- 2. CONVENIO (CU-MPD-01)
--------------------------------------------------------------------------------

CREATE SEQUENCE CONVENIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE CONVENIO (
    ID_CONVENIO         NUMBER(19)      NOT NULL,
    NUMERO_CONVENIO     VARCHAR2(50)    NOT NULL,
    NOMBRE_CONVENIO     VARCHAR2(300)   NOT NULL,
    MONTO_CONVENIO      NUMBER(18,2)    NOT NULL,
    MONEDA              VARCHAR2(10)    DEFAULT 'USD' NOT NULL,
    TIPO_FINANCIAMIENTO VARCHAR2(20)    DEFAULT 'PRESTAMO_EXTERNO' NOT NULL,
    ID_ORGANISMO_ACREEDOR NUMBER(19)    NOT NULL,
    ID_INSTITUCION_EJECUTORA NUMBER(19) NOT NULL,
    OBJETIVO_CONVENIO   VARCHAR2(2000),
    MONTO_CONTRAPARTIDA NUMBER(18,2),
    VALOR_TASA          NUMBER(6,3),
    COMISION_COMPROMISO NUMBER(6,3),
    FECHA_APROBACION_DECRETO DATE,
    FECHA_ULTIMO_DESEMBOLSO  DATE,
    ESTADO              VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    FECHA_ELIMINACION   TIMESTAMP,
    JUSTIFICACION_ELIMINACION VARCHAR2(2000),
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    FECHA_MODIFICACION  TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR2(100),
    CONSTRAINT PK_CONVENIO PRIMARY KEY (ID_CONVENIO),
    CONSTRAINT UK_CONVENIO_NUM_NOMBRE UNIQUE (NUMERO_CONVENIO, NOMBRE_CONVENIO),
    CONSTRAINT FK_CONVENIO_ORGANISMO FOREIGN KEY (ID_ORGANISMO_ACREEDOR) REFERENCES ORGANISMO_ACREEDOR (ID_ORGANISMO_ACREEDOR),
    CONSTRAINT FK_CONVENIO_INSTITUCION FOREIGN KEY (ID_INSTITUCION_EJECUTORA) REFERENCES INSTITUCION (ID_INSTITUCION),
    CONSTRAINT CK_CONVENIO_TIPO_FIN CHECK (TIPO_FINANCIAMIENTO IN ('PRESTAMO_EXTERNO','DONACION')),
    CONSTRAINT CK_CONVENIO_ESTADO CHECK (ESTADO IN ('ACTIVO','ELIMINADO'))
);
COMMENT ON TABLE CONVENIO IS 'Convenio de prestamo externo o donacion. CU-MPD-01. RN01: Nombre+No.Convenio unicos.';

CREATE SEQUENCE INST_COEJECUTORA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE INSTITUCION_COEJECUTORA (
    ID_INST_COEJECUTORA NUMBER(19)      NOT NULL,
    ID_CONVENIO         NUMBER(19)      NOT NULL,
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    CONSTRAINT PK_INST_COEJECUTORA PRIMARY KEY (ID_INST_COEJECUTORA),
    CONSTRAINT UK_INST_COEJECUTORA UNIQUE (ID_CONVENIO, ID_INSTITUCION),
    CONSTRAINT FK_INST_COEJEC_CONVENIO FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO (ID_CONVENIO),
    CONSTRAINT FK_INST_COEJEC_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION)
);
COMMENT ON TABLE INSTITUCION_COEJECUTORA IS 'Instituciones coejecutoras adicionales de un convenio (N:M). CU-MPD-01, RN09';

CREATE SEQUENCE CONDICION_PREVIA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE CONDICION_PREVIA (
    ID_CONDICION_PREVIA NUMBER(19)      NOT NULL,
    ID_CONVENIO         NUMBER(19)      NOT NULL,
    NUMERO              NUMBER(6)       NOT NULL,
    DESCRIPCION         VARCHAR2(2000)  NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'PENDIENTE' NOT NULL,
    FECHA_CUMPLIMIENTO  DATE,
    COMENTARIOS         VARCHAR2(2000),
    FINALIZADA          NUMBER(1)       DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CONDICION_PREVIA PRIMARY KEY (ID_CONDICION_PREVIA),
    CONSTRAINT UK_CONDICION_PREVIA_NUM UNIQUE (ID_CONVENIO, NUMERO),
    CONSTRAINT FK_CONDICION_PREVIA_CONVENIO FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO (ID_CONVENIO),
    CONSTRAINT CK_CONDICION_PREVIA_ESTADO CHECK (ESTADO IN ('PENDIENTE','CUMPLIDA'))
);
COMMENT ON TABLE CONDICION_PREVIA IS 'Condicion previa de desembolso del convenio, numeracion correlativa. CU-MPD-01, CU-MPD-04';

CREATE SEQUENCE COMPONENTE_CONVENIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE COMPONENTE_CONVENIO (
    ID_COMPONENTE_CONVENIO NUMBER(19)   NOT NULL,
    ID_CONVENIO         NUMBER(19)      NOT NULL,
    NOMBRE_COMPONENTE    VARCHAR2(250)  NOT NULL,
    MONTO_ASIGNADO       NUMBER(18,2)   NOT NULL,
    PORCENTAJE           NUMBER(5,2),
    CONSTRAINT PK_COMPONENTE_CONVENIO PRIMARY KEY (ID_COMPONENTE_CONVENIO),
    CONSTRAINT FK_COMPONENTE_CONV_CONVENIO FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO (ID_CONVENIO)
);
COMMENT ON TABLE COMPONENTE_CONVENIO IS 'Distribucion inicial del monto del convenio por componente. CU-MPD-01. RN22: suma <= monto convenio.';

CREATE SEQUENCE DOC_ADJUNTO_CONVENIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE DOCUMENTO_ADJUNTO_CONVENIO (
    ID_DOCUMENTO_ADJUNTO NUMBER(19)     NOT NULL,
    ID_CONVENIO         NUMBER(19)      NOT NULL,
    SECCION             VARCHAR2(30)    NOT NULL,
    NOMBRE_ARCHIVO       VARCHAR2(300)  NOT NULL,
    RUTA_ARCHIVO         VARCHAR2(500)  NOT NULL,
    USUARIO_CARGA        VARCHAR2(100),
    FECHA_CARGA          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DOC_ADJUNTO_CONVENIO PRIMARY KEY (ID_DOCUMENTO_ADJUNTO),
    CONSTRAINT FK_DOC_ADJ_CONV_CONVENIO FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO (ID_CONVENIO),
    CONSTRAINT CK_DOC_ADJ_CONV_SECCION CHECK (SECCION IN ('INFORMACION_GENERAL','FECHAS','CONDICIONES_PREVIAS'))
);
COMMENT ON TABLE DOCUMENTO_ADJUNTO_CONVENIO IS 'Documento adjunto en Info General/Fechas/Condiciones Previas del convenio. CU-MPD-01';

--------------------------------------------------------------------------------
-- 3. MODIFICACIONES AL CONVENIO (CU-MPD-03)
--------------------------------------------------------------------------------

CREATE SEQUENCE AJUSTE_CONVENIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE AJUSTE_CONVENIO (
    ID_AJUSTE_CONVENIO  NUMBER(19)      NOT NULL,
    ID_CONVENIO         NUMBER(19)      NOT NULL,
    TIPO_AJUSTE         VARCHAR2(20)    NOT NULL,
    DOCUMENTO_AUTORIZACION VARCHAR2(500),
    JUSTIFICACION        VARCHAR2(2000),
    FECHA_AJUSTE         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AJUSTE_CONVENIO PRIMARY KEY (ID_AJUSTE_CONVENIO),
    CONSTRAINT FK_AJUSTE_CONVENIO_CONV FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO (ID_CONVENIO),
    CONSTRAINT CK_AJUSTE_CONVENIO_TIPO CHECK (TIPO_AJUSTE IN ('ADENDA','REESTRUCTURACION','NA'))
);
COMMENT ON TABLE AJUSTE_CONVENIO IS 'Ajuste (adenda/reestructuracion) sobre un convenio. CU-MPD-03';

CREATE SEQUENCE COMP_CONV_AJUSTE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE COMPONENTE_CONVENIO_AJUSTE (
    ID_COMPONENTE_AJUSTE NUMBER(19)     NOT NULL,
    ID_AJUSTE_CONVENIO  NUMBER(19)      NOT NULL,
    ID_COMPONENTE_CONVENIO NUMBER(19),
    NOMBRE_COMPONENTE    VARCHAR2(250)  NOT NULL,
    MONTO_ASIGNADO_INICIAL NUMBER(18,2) NOT NULL,
    MONTO_ASIGNADO_AJUSTADO NUMBER(18,2) NOT NULL,
    PORCENTAJE           NUMBER(5,2),
    CONSTRAINT PK_COMP_CONV_AJUSTE PRIMARY KEY (ID_COMPONENTE_AJUSTE),
    CONSTRAINT FK_COMP_CONV_AJUSTE FOREIGN KEY (ID_AJUSTE_CONVENIO) REFERENCES AJUSTE_CONVENIO (ID_AJUSTE_CONVENIO),
    CONSTRAINT FK_COMP_CONV_AJ_ORIGEN FOREIGN KEY (ID_COMPONENTE_CONVENIO) REFERENCES COMPONENTE_CONVENIO (ID_COMPONENTE_CONVENIO)
);
COMMENT ON TABLE COMPONENTE_CONVENIO_AJUSTE IS 'Distribucion ajustada (inicial vs ajustada) de un componente. CU-MPD-03. RN07: suma = monto convenio.';

CREATE SEQUENCE AMPLIACION_PLAZO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE AMPLIACION_PLAZO_CONVENIO (
    ID_AMPLIACION_PLAZO NUMBER(19)      NOT NULL,
    ID_CONVENIO         NUMBER(19)      NOT NULL,
    FECHA_AMPLIACION_DESEMBOLSO DATE    NOT NULL,
    PERIODO_AJUSTADO_CALCULADO VARCHAR2(100),
    DOCUMENTO_AUTORIZACION VARCHAR2(500),
    FECHA_REGISTRO        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AMPLIACION_PLAZO PRIMARY KEY (ID_AMPLIACION_PLAZO),
    CONSTRAINT FK_AMPLIACION_PLAZO_CONV FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO (ID_CONVENIO)
);
COMMENT ON TABLE AMPLIACION_PLAZO_CONVENIO IS 'Ampliacion de plazo del ultimo desembolso del convenio. CU-MPD-03';

--------------------------------------------------------------------------------
-- 4. FICHA DEL CONVENIO — PROYECTOS ASOCIADOS (CU-MPD-04)
--------------------------------------------------------------------------------

CREATE SEQUENCE PROYECTO_CONVENIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PROYECTO_CONVENIO (
    ID_PROYECTO_CONVENIO NUMBER(19)     NOT NULL,
    ID_CONVENIO         NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    MONTO_COMPROMETIDO   NUMBER(18,2)   DEFAULT 0 NOT NULL,
    ES_PROGRAMA_PRINCIPAL NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PROYECTO_CONVENIO PRIMARY KEY (ID_PROYECTO_CONVENIO),
    CONSTRAINT UK_PROYECTO_CONVENIO UNIQUE (ID_CONVENIO, ID_PROYECTO),
    CONSTRAINT FK_PROY_CONV_CONVENIO FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO (ID_CONVENIO),
    CONSTRAINT FK_PROY_CONV_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE PROYECTO_CONVENIO IS 'Proyecto vinculado al convenio, con monto comprometido y bandera de Programa Principal. CU-MPD-04';

--------------------------------------------------------------------------------
-- 5. CIERRE DE SUPUESTOS PENDIENTES DEL MÓDULO PROGRAMACIÓN
-- Agrega las FK reales a ID_CONVENIO que quedaron pendientes en schema_programacion.sql
--------------------------------------------------------------------------------

ALTER TABLE FINANCIAMIENTO_PRIPME
    ADD CONSTRAINT FK_FIN_PRIPME_CONVENIO FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO (ID_CONVENIO);

ALTER TABLE PROGRAMACION_FINANCIERA_PAIP
    ADD CONSTRAINT FK_PROG_FIN_PAIP_CONVENIO FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO (ID_CONVENIO);

--------------------------------------------------------------------------------
-- FIN DEL SCRIPT - Módulo Convenios de Financiamiento
--------------------------------------------------------------------------------
