--------------------------------------------------------------------------------
-- SIIP - Sistema de Información de Inversión Pública de El Salvador
-- Esquema Oracle - Módulo Ejecución y Seguimiento del PAIP (M-12)
-- Depende de: schema_preinversion.sql (PROYECTO, INSTITUCION, USUARIO, DEPARTAMENTO, MUNICIPIO)
--             schema_programacion.sql (PRODUCTO, INDICADOR_PRODUCTO, PERIODO_PROGRAMACION_PAIP,
--                                       PERIODO_PROGRAMACION_PAP)
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. AVANCE FINANCIERO MENSUAL (EJE-01)
--------------------------------------------------------------------------------

CREATE SEQUENCE EJEC_FIN_MENSUAL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE EJECUCION_FINANCIERA_MENSUAL (
    ID_EJECUCION_FIN_MENSUAL NUMBER(19) NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    MES                 NUMBER(2)       NOT NULL,
    MONTO_COMPROMETIDO  NUMBER(18,2)    DEFAULT 0 NOT NULL,
    MONTO_PAGADO        NUMBER(18,2)    DEFAULT 0 NOT NULL,
    EJECUCION_FINANCIERA NUMBER(18,2)   DEFAULT 0 NOT NULL,
    EJECUCION_PROVISION  NUMBER(18,2)   DEFAULT 0 NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'REGISTRADO' NOT NULL,
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    CONSTRAINT PK_EJEC_FIN_MENSUAL PRIMARY KEY (ID_EJECUCION_FIN_MENSUAL),
    CONSTRAINT UK_EJEC_FIN_MENSUAL UNIQUE (ID_PROYECTO, ANIO, MES),
    CONSTRAINT FK_EJEC_FIN_MENSUAL_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_EJEC_FIN_MENSUAL_MES CHECK (MES BETWEEN 1 AND 12),
    CONSTRAINT CK_EJEC_FIN_MENSUAL_ESTADO CHECK (ESTADO IN ('REGISTRADO','FINALIZADO','REVISADO'))
);
COMMENT ON TABLE EJECUCION_FINANCIERA_MENSUAL IS 'Avance financiero mensual del proyecto en el PAIP. CU-EJE-01';

CREATE SEQUENCE OBS_EJEC_FIN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE OBSERVACION_EJECUCION_FINANCIERA (
    ID_OBSERVACION_EJEC_FIN NUMBER(19)  NOT NULL,
    ID_EJECUCION_FIN_MENSUAL NUMBER(19) NOT NULL,
    ID_AUTOR            NUMBER(19)      NOT NULL,
    TIPO_OBSERVACION    VARCHAR2(20)    NOT NULL,
    TEXTO               VARCHAR2(2000)  NOT NULL,
    FECHA               TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_OBS_EJEC_FIN PRIMARY KEY (ID_OBSERVACION_EJEC_FIN),
    CONSTRAINT FK_OBS_EJEC_FIN_EJEC FOREIGN KEY (ID_EJECUCION_FIN_MENSUAL) REFERENCES EJECUCION_FINANCIERA_MENSUAL (ID_EJECUCION_FIN_MENSUAL),
    CONSTRAINT FK_OBS_EJEC_FIN_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT CK_OBS_EJEC_FIN_TIPO CHECK (TIPO_OBSERVACION IN ('PRESUPUESTO','PROVISION'))
);
COMMENT ON TABLE OBSERVACION_EJECUCION_FINANCIERA IS 'Observacion del Tecnico SYMP sobre presupuesto/provision. CU-EJE-01';

--------------------------------------------------------------------------------
-- 2. AVANCE FÍSICO MENSUAL (EJE-02)
--------------------------------------------------------------------------------

CREATE SEQUENCE AVANCE_FISICO_MENSUAL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE AVANCE_FISICO_MENSUAL (
    ID_AVANCE_FISICO_MENSUAL NUMBER(19) NOT NULL,
    ID_INDICADOR_PRODUCTO NUMBER(19)    NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    MES                 NUMBER(2)       NOT NULL,
    AVANCE_MENSUAL      NUMBER(18,2)    NOT NULL,
    AVANCE_ACUMULADO    NUMBER(18,2),
    JUSTIFICACION_RETRASO VARCHAR2(2000),
    CONSTRAINT PK_AVANCE_FISICO_MENSUAL PRIMARY KEY (ID_AVANCE_FISICO_MENSUAL),
    CONSTRAINT UK_AVANCE_FISICO_MENSUAL UNIQUE (ID_INDICADOR_PRODUCTO, ANIO, MES),
    CONSTRAINT FK_AVANCE_FIS_MENSUAL_IND FOREIGN KEY (ID_INDICADOR_PRODUCTO) REFERENCES INDICADOR_PRODUCTO (ID_INDICADOR_PRODUCTO),
    CONSTRAINT CK_AVANCE_FIS_MENSUAL_MES CHECK (MES BETWEEN 1 AND 12)
);
COMMENT ON TABLE AVANCE_FISICO_MENSUAL IS 'Avance fisico mensual de un indicador de producto. CU-EJE-02';

--------------------------------------------------------------------------------
-- 3. AVANCE FINANCIERO POR UBICACIÓN GEOGRÁFICA (EJE-03)
--------------------------------------------------------------------------------

CREATE SEQUENCE EJEC_FIN_UBICACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE EJECUCION_FINANCIERA_UBICACION (
    ID_EJEC_FIN_UBICACION NUMBER(19)    NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ID_DEPARTAMENTO     NUMBER(19)      NOT NULL,
    ID_MUNICIPIO        NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    MES                 NUMBER(2)       NOT NULL,
    MONTO_EJECUTADO     NUMBER(18,2)    DEFAULT 0 NOT NULL,
    MONTO_PROVISION_EJECUTADA NUMBER(18,2) DEFAULT 0 NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'REGISTRADO' NOT NULL,
    OBSERVACION         VARCHAR2(2000),
    CONSTRAINT PK_EJEC_FIN_UBICACION PRIMARY KEY (ID_EJEC_FIN_UBICACION),
    CONSTRAINT UK_EJEC_FIN_UBICACION UNIQUE (ID_PROYECTO, ID_MUNICIPIO, ANIO, MES),
    CONSTRAINT FK_EJEC_FIN_UBIC_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_EJEC_FIN_UBIC_DEPTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO),
    CONSTRAINT FK_EJEC_FIN_UBIC_MUNICIPIO FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_MUNICIPIO),
    CONSTRAINT CK_EJEC_FIN_UBIC_MES CHECK (MES BETWEEN 1 AND 12),
    CONSTRAINT CK_EJEC_FIN_UBIC_ESTADO CHECK (ESTADO IN ('REGISTRADO','FINALIZADO','REVISADO'))
);
COMMENT ON TABLE EJECUCION_FINANCIERA_UBICACION IS 'Avance financiero por ubicacion geografica del proyecto. CU-EJE-03';

--------------------------------------------------------------------------------
-- 4. PROCESOS ADMINISTRATIVOS Y CONTRATOS (EJE-04)
--------------------------------------------------------------------------------

CREATE SEQUENCE PROCESO_ADMIN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PROCESO_ADMINISTRATIVO (
    ID_PROCESO_ADMINISTRATIVO NUMBER(19) NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ID_PROCESO_EXTERNO  VARCHAR2(50),
    NOMBRE              VARCHAR2(300)   NOT NULL,
    METODO_CONTRATACION VARCHAR2(100),
    CATEGORIA           VARCHAR2(100),
    ESTADO              VARCHAR2(30)    NOT NULL,
    MONTO_PROGRAMADO    NUMBER(18,2),
    MONTO_COMPROMETIDO  NUMBER(18,2),
    MONTO_PENDIENTE     NUMBER(18,2),
    ANIO                NUMBER(4)       NOT NULL,
    MES                 NUMBER(2)       NOT NULL,
    JUSTIFICACION_SIN_CONTRATO VARCHAR2(2000),
    CONSTRAINT PK_PROCESO_ADMIN PRIMARY KEY (ID_PROCESO_ADMINISTRATIVO),
    CONSTRAINT FK_PROCESO_ADMIN_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_PROCESO_ADMIN_MES CHECK (MES BETWEEN 1 AND 12)
);
COMMENT ON TABLE PROCESO_ADMINISTRATIVO IS 'Hito de un proceso de adquisicion asociado a un proyecto. CU-EJE-04';

CREATE SEQUENCE CONTRATO_PROC_ADMIN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE CONTRATO_PROCESO_ADMINISTRATIVO (
    ID_CONTRATO         NUMBER(19)      NOT NULL,
    ID_PROCESO_ADMINISTRATIVO NUMBER(19) NOT NULL,
    ID_CONTRATO_EXTERNO VARCHAR2(50)    NOT NULL,
    MONTO               NUMBER(18,2)    NOT NULL,
    FECHA_INICIO        DATE,
    FECHA_TERMINO       DATE,
    ESTADO              VARCHAR2(30)    NOT NULL,
    CONSTRAINT PK_CONTRATO_PROC_ADMIN PRIMARY KEY (ID_CONTRATO),
    CONSTRAINT FK_CONTRATO_PROC_ADMIN FOREIGN KEY (ID_PROCESO_ADMINISTRATIVO) REFERENCES PROCESO_ADMINISTRATIVO (ID_PROCESO_ADMINISTRATIVO),
    CONSTRAINT CK_CONTRATO_PROC_ADMIN_ESTADO CHECK (ESTADO IN ('EN_EJECUCION','FINALIZADO'))
);
COMMENT ON TABLE CONTRATO_PROCESO_ADMINISTRATIVO IS 'Contrato derivado de un proceso administrativo. CU-EJE-04';

--------------------------------------------------------------------------------
-- 5. MONITOREO DEL AVANCE MENSUAL DEL PAIP (EJE-05)
--------------------------------------------------------------------------------

CREATE SEQUENCE REVISION_EJEC_PAIP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE REVISION_EJECUCION_PAIP (
    ID_REVISION_EJEC_PAIP NUMBER(19)    NOT NULL,
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    ID_PERIODO_PAIP     NUMBER(19)      NOT NULL,
    MES                 NUMBER(2)       NOT NULL,
    TIPO_REVISION       VARCHAR2(20)    NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'SIN_REVISAR' NOT NULL,
    FECHA_REVISION      TIMESTAMP,
    CONSTRAINT PK_REVISION_EJEC_PAIP PRIMARY KEY (ID_REVISION_EJEC_PAIP),
    CONSTRAINT UK_REVISION_EJEC_PAIP UNIQUE (ID_INSTITUCION, ID_PERIODO_PAIP, MES, TIPO_REVISION),
    CONSTRAINT FK_REV_EJEC_PAIP_INST FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    CONSTRAINT FK_REV_EJEC_PAIP_PERIODO FOREIGN KEY (ID_PERIODO_PAIP) REFERENCES PERIODO_PROGRAMACION_PAIP (ID_PERIODO_PAIP),
    CONSTRAINT CK_REV_EJEC_PAIP_MES CHECK (MES BETWEEN 1 AND 12),
    CONSTRAINT CK_REV_EJEC_PAIP_TIPO CHECK (TIPO_REVISION IN ('FINANCIERO','FISICO','GEOGRAFICO')),
    CONSTRAINT CK_REV_EJEC_PAIP_ESTADO CHECK (ESTADO IN ('REVISADO','SIN_REVISAR'))
);
COMMENT ON TABLE REVISION_EJECUCION_PAIP IS 'Estado de revision del avance mensual del PAIP por institucion. CU-EJE-05';

--------------------------------------------------------------------------------
-- 6. INFORME DE VISITA DE CAMPO (EJE-06)
--------------------------------------------------------------------------------

CREATE SEQUENCE INFORME_VISITA_CAMPO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE INFORME_VISITA_CAMPO (
    ID_INFORME_VISITA   NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ID_TECNICO_RESPONSABLE NUMBER(19)   NOT NULL,
    FECHA_VISITA        DATE            NOT NULL,
    AVANCE_OBSERVADO    VARCHAR2(2000),
    COMENTARIOS         CLOB,
    CONCLUSIONES        CLOB,
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    CONSTRAINT PK_INFORME_VISITA_CAMPO PRIMARY KEY (ID_INFORME_VISITA),
    CONSTRAINT FK_INFORME_VISITA_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_INFORME_VISITA_TECNICO FOREIGN KEY (ID_TECNICO_RESPONSABLE) REFERENCES USUARIO (ID_USUARIO)
);
COMMENT ON TABLE INFORME_VISITA_CAMPO IS 'Informe de visita de campo a un proyecto. CU-EJE-06';

CREATE SEQUENCE ACOMPANANTE_VISITA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ACOMPANANTE_VISITA_CAMPO (
    ID_ACOMPANANTE      NUMBER(19)      NOT NULL,
    ID_INFORME_VISITA   NUMBER(19)      NOT NULL,
    INSTITUCION         VARCHAR2(250),
    NOMBRE              VARCHAR2(250)   NOT NULL,
    CARGO               VARCHAR2(150),
    CONSTRAINT PK_ACOMPANANTE_VISITA PRIMARY KEY (ID_ACOMPANANTE),
    CONSTRAINT FK_ACOMPANANTE_INFORME FOREIGN KEY (ID_INFORME_VISITA) REFERENCES INFORME_VISITA_CAMPO (ID_INFORME_VISITA)
);
COMMENT ON TABLE ACOMPANANTE_VISITA_CAMPO IS 'Persona que acompano la visita de campo. CU-EJE-06';

CREATE SEQUENCE ARCHIVO_VISITA_CAMPO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ARCHIVO_ADJUNTO_VISITA_CAMPO (
    ID_ARCHIVO_ADJUNTO  NUMBER(19)      NOT NULL,
    ID_INFORME_VISITA   NUMBER(19)      NOT NULL,
    NOMBRE_ARCHIVO      VARCHAR2(300)   NOT NULL,
    RUTA_ARCHIVO        VARCHAR2(500)   NOT NULL,
    TIPO_ARCHIVO        VARCHAR2(20),
    FECHA_CARGA         TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO_CARGA       VARCHAR2(100),
    CONSTRAINT PK_ARCHIVO_VISITA_CAMPO PRIMARY KEY (ID_ARCHIVO_ADJUNTO),
    CONSTRAINT FK_ARCHIVO_VISITA_INFORME FOREIGN KEY (ID_INFORME_VISITA) REFERENCES INFORME_VISITA_CAMPO (ID_INFORME_VISITA)
);
COMMENT ON TABLE ARCHIVO_ADJUNTO_VISITA_CAMPO IS 'Documentos/fotos adjuntos al informe de visita de campo. CU-EJE-06';

--------------------------------------------------------------------------------
-- 7. CONCLUSIÓN Y CIERRE FÍSICO Y FINANCIERO DE PROYECTOS (EJE-07)
--------------------------------------------------------------------------------

CREATE SEQUENCE CIERRE_PROYECTO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE CIERRE_PROYECTO (
    ID_CIERRE_PROYECTO  NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    CIERRE_FISICO       NUMBER(1)       DEFAULT 0 NOT NULL,
    CIERRE_FINANCIERO   NUMBER(1)       DEFAULT 0 NOT NULL,
    FECHA_CIERRE        TIMESTAMP,
    OBSERVACION_REVISION_SYMP VARCHAR2(2000),
    MOTIVO_REACTIVACION  VARCHAR2(2000),
    CONSTRAINT PK_CIERRE_PROYECTO PRIMARY KEY (ID_CIERRE_PROYECTO),
    CONSTRAINT UK_CIERRE_PROYECTO UNIQUE (ID_PROYECTO),
    CONSTRAINT FK_CIERRE_PROYECTO_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE CIERRE_PROYECTO IS 'Estado de cierre fisico/financiero del proyecto. CU-EJE-07';

CREATE SEQUENCE DOC_RESPALDO_CIERRE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE DOCUMENTO_RESPALDO_CIERRE (
    ID_DOCUMENTO_RESPALDO NUMBER(19)    NOT NULL,
    ID_CIERRE_PROYECTO  NUMBER(19)      NOT NULL,
    TIPO_DOCUMENTO       VARCHAR2(150),
    NOMBRE_ARCHIVO       VARCHAR2(300)  NOT NULL,
    RUTA_ARCHIVO         VARCHAR2(500)  NOT NULL,
    USUARIO_CARGA        VARCHAR2(100),
    FECHA_CARGA          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DOC_RESPALDO_CIERRE PRIMARY KEY (ID_DOCUMENTO_RESPALDO),
    CONSTRAINT FK_DOC_RESPALDO_CIERRE FOREIGN KEY (ID_CIERRE_PROYECTO) REFERENCES CIERRE_PROYECTO (ID_CIERRE_PROYECTO)
);
COMMENT ON TABLE DOCUMENTO_RESPALDO_CIERRE IS 'Documento de evidencia del cierre del proyecto. CU-EJE-07';

CREATE SEQUENCE HISTORIAL_CIERRE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE HISTORIAL_CIERRE (
    ID_HISTORIAL_CIERRE NUMBER(19)      NOT NULL,
    ID_CIERRE_PROYECTO  NUMBER(19)      NOT NULL,
    ID_USUARIO          NUMBER(19)      NOT NULL,
    FECHA_HORA          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    OBSERVACIONES       VARCHAR2(2000),
    CONSTRAINT PK_HISTORIAL_CIERRE PRIMARY KEY (ID_HISTORIAL_CIERRE),
    CONSTRAINT FK_HIST_CIERRE_CIERRE FOREIGN KEY (ID_CIERRE_PROYECTO) REFERENCES CIERRE_PROYECTO (ID_CIERRE_PROYECTO),
    CONSTRAINT FK_HIST_CIERRE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);
COMMENT ON TABLE HISTORIAL_CIERRE IS 'Trazabilidad cronologica de ajustes durante el cierre del proyecto. CU-EJE-07';

--------------------------------------------------------------------------------
-- 8. MONITOREO DEL AVANCE CUATRIMESTRAL DEL PAP (EJE-10)
--------------------------------------------------------------------------------

CREATE SEQUENCE REVISION_AVANCE_PAP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE REVISION_AVANCE_CUATRI_PAP (
    ID_REVISION_AVANCE_PAP NUMBER(19)   NOT NULL,
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    ID_PERIODO_PAP      NUMBER(19)      NOT NULL,
    TIPO_REVISION       VARCHAR2(20)    NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'SIN_REVISAR' NOT NULL,
    FECHA_REVISION      TIMESTAMP,
    CONSTRAINT PK_REVISION_AVANCE_PAP PRIMARY KEY (ID_REVISION_AVANCE_PAP),
    CONSTRAINT UK_REVISION_AVANCE_PAP UNIQUE (ID_INSTITUCION, ID_PERIODO_PAP, TIPO_REVISION),
    CONSTRAINT FK_REV_AVANCE_PAP_INST FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    CONSTRAINT FK_REV_AVANCE_PAP_PERIODO FOREIGN KEY (ID_PERIODO_PAP) REFERENCES PERIODO_PROGRAMACION_PAP (ID_PERIODO_PAP),
    CONSTRAINT CK_REV_AVANCE_PAP_TIPO CHECK (TIPO_REVISION IN ('FINANCIERO','METAS')),
    CONSTRAINT CK_REV_AVANCE_PAP_ESTADO CHECK (ESTADO IN ('REVISADO','SIN_REVISAR'))
);
COMMENT ON TABLE REVISION_AVANCE_CUATRI_PAP IS 'Estado de revision del AVANCE cuatrimestral del PAP (distinto de la programacion, CU-PRO-25). CU-EJE-10';

--------------------------------------------------------------------------------
-- 9. SEGUIMIENTO MENSUAL DE PROYECTOS - ESTATUS (EJE-11)
--------------------------------------------------------------------------------

CREATE SEQUENCE SEGUIMIENTO_ESTATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE SEGUIMIENTO_MENSUAL_ESTATUS (
    ID_SEGUIMIENTO_ESTATUS NUMBER(19)   NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    MES                 NUMBER(2)       NOT NULL,
    ESTATUS             VARCHAR2(2000)  NOT NULL,
    ID_AUTOR            NUMBER(19)      NOT NULL,
    FECHA_REGISTRO      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SEGUIMIENTO_ESTATUS PRIMARY KEY (ID_SEGUIMIENTO_ESTATUS),
    CONSTRAINT UK_SEGUIMIENTO_ESTATUS UNIQUE (ID_PROYECTO, ANIO, MES),
    CONSTRAINT FK_SEGUIM_ESTATUS_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_SEGUIM_ESTATUS_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT CK_SEGUIM_ESTATUS_MES CHECK (MES BETWEEN 1 AND 12)
);
COMMENT ON TABLE SEGUIMIENTO_MENSUAL_ESTATUS IS 'Estatus textual mensual del proyecto, registrado por el Tecnico SYMP. CU-EJE-11';

--------------------------------------------------------------------------------
-- FIN DEL SCRIPT - Módulo Ejecución y Seguimiento del PAIP
--------------------------------------------------------------------------------
