-- V001__crear_tablas_catalogo.sql
-- Autor: equipo SIIP
-- Fecha: 2026-09-29
-- Descripción: CU-ADM-01 (Administración de Catálogos). Tablas del catalogMaster: catálogos, la
--   definición de sus campos (FIELD/KEY) y sus registros. Corresponde 1:1 a las entidades de
--   infrastructure/persistence/entity/catalogo; la aplicación corre con ddl-auto: none.
--   Ejecutar conectado como el esquema dueño de las tablas (sin prefijo de esquema).

CREATE SEQUENCE CATALOGO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CAMPO_DEFINICION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE REGISTRO_CATALOGO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CATALOGO (
    ID_CATALOGO           NUMBER(19)    NOT NULL,
    CODIGO                VARCHAR2(100) NOT NULL,
    NOMBRE                VARCHAR2(300) NOT NULL,
    CATALOGO_PADRE_CODIGO VARCHAR2(100),
    ESTADO                VARCHAR2(20)  NOT NULL,
    FECHA_DESDE           DATE,
    FECHA_HASTA           DATE,
    CONSTRAINT PK_CATALOGO PRIMARY KEY (ID_CATALOGO),
    CONSTRAINT UK_CATALOGO_CODIGO UNIQUE (CODIGO),
    CONSTRAINT CK_CATALOGO_ESTADO CHECK (ESTADO IN ('ACTIVE', 'INACTIVE'))
);

COMMENT ON TABLE CATALOGO IS 'CU-ADM-01: catálogos del catalogMaster';
COMMENT ON COLUMN CATALOGO.CATALOGO_PADRE_CODIGO IS 'Código del catálogo padre (referencia por código de negocio, sin FK)';
COMMENT ON COLUMN CATALOGO.ESTADO IS 'ACTIVE / INACTIVE; el estado efectivo considera además FECHA_HASTA (Regla 14)';

CREATE INDEX IDX_CATALOGO_PADRE ON CATALOGO (CATALOGO_PADRE_CODIGO);

CREATE TABLE CAMPO_DEFINICION (
    ID_CAMPO_DEFINICION NUMBER(19)    NOT NULL,
    ID_CATALOGO         NUMBER(19)    NOT NULL,
    NOMBRE              VARCHAR2(150) NOT NULL,
    TIPO                VARCHAR2(20)  NOT NULL,
    ES_KEY              NUMBER(1)     NOT NULL,
    POSICION            NUMBER(10),
    CONSTRAINT PK_CAMPO_DEFINICION PRIMARY KEY (ID_CAMPO_DEFINICION),
    CONSTRAINT FK_CAMPO_DEFINICION_CATALOGO FOREIGN KEY (ID_CATALOGO) REFERENCES CATALOGO (ID_CATALOGO),
    CONSTRAINT CK_CAMPO_DEFINICION_TIPO CHECK (TIPO IN ('NUMBER', 'STRING', 'DATE', 'ENUM')),
    CONSTRAINT CK_CAMPO_DEFINICION_ES_KEY CHECK (ES_KEY IN (0, 1))
);

COMMENT ON TABLE CAMPO_DEFINICION IS 'CU-ADM-01: campos (FIELD/KEY) de un catálogo';
COMMENT ON COLUMN CAMPO_DEFINICION.ES_KEY IS '1=KEY (identifica al registro), 0=FIELD';
COMMENT ON COLUMN CAMPO_DEFINICION.POSICION IS 'Orden del campo desde 1 (Reglas 4 y 5); nulo en catálogos anteriores al contrato';

CREATE INDEX IDX_CAMPO_DEFINICION_CATALOGO ON CAMPO_DEFINICION (ID_CATALOGO);

CREATE TABLE CAMPO_DEFINICION_VALOR_ENUM (
    ID_CAMPO_DEFINICION NUMBER(19)    NOT NULL,
    ORDEN               NUMBER(10)    NOT NULL,
    VALOR               VARCHAR2(200),
    CONSTRAINT PK_CAMPO_DEFINICION_VALOR_ENUM PRIMARY KEY (ID_CAMPO_DEFINICION, ORDEN),
    CONSTRAINT FK_CAMPO_VALOR_ENUM_CAMPO FOREIGN KEY (ID_CAMPO_DEFINICION)
        REFERENCES CAMPO_DEFINICION (ID_CAMPO_DEFINICION)
);

COMMENT ON TABLE CAMPO_DEFINICION_VALOR_ENUM IS 'CU-ADM-01: valores permitidos de un campo ENUM (aún sin uso en el CU)';

CREATE TABLE REGISTRO_CATALOGO (
    ID_REGISTRO       NUMBER(19)    NOT NULL,
    ID_CATALOGO       NUMBER(19)    NOT NULL,
    CLAVE             VARCHAR2(200) NOT NULL,
    ID_REGISTRO_PADRE NUMBER(19),
    ESTADO            VARCHAR2(20)  NOT NULL,
    FECHA_DESDE       DATE,
    FECHA_HASTA       DATE,
    CONSTRAINT PK_REGISTRO_CATALOGO PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT UK_REGISTRO_CATALOGO_CLAVE UNIQUE (ID_CATALOGO, CLAVE),
    CONSTRAINT FK_REGISTRO_CATALOGO_CATALOGO FOREIGN KEY (ID_CATALOGO) REFERENCES CATALOGO (ID_CATALOGO),
    CONSTRAINT FK_REGISTRO_CATALOGO_PADRE FOREIGN KEY (ID_REGISTRO_PADRE) REFERENCES REGISTRO_CATALOGO (ID_REGISTRO),
    CONSTRAINT CK_REGISTRO_CATALOGO_ESTADO CHECK (ESTADO IN ('ACTIVE', 'INACTIVE'))
);

COMMENT ON TABLE REGISTRO_CATALOGO IS 'CU-ADM-01: registros de un catálogo';
COMMENT ON COLUMN REGISTRO_CATALOGO.CLAVE IS 'Valor del campo KEY del registro, único por catálogo';
COMMENT ON COLUMN REGISTRO_CATALOGO.ID_REGISTRO_PADRE IS 'Registro del catálogo padre al que se enlaza (Regla 23)';

CREATE INDEX IDX_REGISTRO_CATALOGO_PADRE ON REGISTRO_CATALOGO (ID_REGISTRO_PADRE);

CREATE TABLE REGISTRO_VALOR (
    ID_REGISTRO  NUMBER(19)     NOT NULL,
    NOMBRE_CAMPO VARCHAR2(255)  NOT NULL,
    VALOR        VARCHAR2(1000),
    CONSTRAINT PK_REGISTRO_VALOR PRIMARY KEY (ID_REGISTRO, NOMBRE_CAMPO),
    CONSTRAINT FK_REGISTRO_VALOR_REGISTRO FOREIGN KEY (ID_REGISTRO) REFERENCES REGISTRO_CATALOGO (ID_REGISTRO)
);

COMMENT ON TABLE REGISTRO_VALOR IS 'CU-ADM-01: valor de cada campo de un registro, como texto';
