-- V002__crear_tablas_calendario.sql
-- Autor: equipo SIIP
-- Fecha: 2026-09-30
-- Descripción: CU-ADM-04 (Gestión de Calendarios). Calendarios laborales, sus períodos
--   LABORAL/NO_LABORAL (con su recurrencia) y sus excepciones por fecha. Corresponde 1:1 a las
--   entidades de infrastructure/persistence/entity/calendario; la aplicación corre con
--   ddl-auto: none. Ejecutar conectado como el esquema dueño de las tablas (sin prefijo de esquema).

CREATE SEQUENCE CALENDARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PERIODO_CALENDARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE EXCEPCION_CALENDARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CALENDARIO (
    ID_CALENDARIO NUMBER(19)     NOT NULL,
    CODIGO        VARCHAR2(100)  NOT NULL,
    NOMBRE        VARCHAR2(300)  NOT NULL,
    DESCRIPCION   VARCHAR2(1000),
    FECHA_INICIO  DATE           NOT NULL,
    FECHA_FIN     DATE           NOT NULL,
    ESTADO        VARCHAR2(20)   NOT NULL,
    ADMINISTRADOR VARCHAR2(100)  NOT NULL,
    CONSTRAINT PK_CALENDARIO PRIMARY KEY (ID_CALENDARIO),
    CONSTRAINT UK_CALENDARIO_CODIGO UNIQUE (CODIGO),
    CONSTRAINT CK_CALENDARIO_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT CK_CALENDARIO_RANGO CHECK (FECHA_INICIO <= FECHA_FIN)
);

COMMENT ON TABLE CALENDARIO IS 'CU-ADM-04: calendarios laborales';
COMMENT ON COLUMN CALENDARIO.FECHA_INICIO IS 'Inicio del período maestro del calendario (RN08, RN10)';
COMMENT ON COLUMN CALENDARIO.FECHA_FIN IS 'Fin del período maestro del calendario (RN08, RN10)';
COMMENT ON COLUMN CALENDARIO.ESTADO IS 'ACTIVO / INACTIVO; nunca se elimina (RN20)';
COMMENT ON COLUMN CALENDARIO.ADMINISTRADOR IS 'preferred_username (Keycloak) del administrador que lo creó (RN12)';

CREATE TABLE PERIODO_CALENDARIO (
    ID_PERIODO       NUMBER(19)    NOT NULL,
    ID_CALENDARIO    NUMBER(19)    NOT NULL,
    CODIGO           VARCHAR2(100) NOT NULL,
    NOMBRE           VARCHAR2(300) NOT NULL,
    TIPO             VARCHAR2(20)  NOT NULL,
    TIPO_RECURRENCIA VARCHAR2(20)  NOT NULL,
    FECHA_INICIO     DATE,
    FECHA_FIN        DATE,
    CONSTRAINT PK_PERIODO_CALENDARIO PRIMARY KEY (ID_PERIODO),
    CONSTRAINT UK_PERIODO_CALENDARIO_CODIGO UNIQUE (ID_CALENDARIO, CODIGO),
    CONSTRAINT FK_PERIODO_CALENDARIO_CAL FOREIGN KEY (ID_CALENDARIO) REFERENCES CALENDARIO (ID_CALENDARIO),
    CONSTRAINT CK_PERIODO_CALENDARIO_TIPO CHECK (TIPO IN ('LABORAL', 'NO_LABORAL')),
    CONSTRAINT CK_PERIODO_CALENDARIO_RECURR CHECK (TIPO_RECURRENCIA IN ('UNA_VEZ', 'SEMANAL', 'MENSUAL')),
    CONSTRAINT CK_PERIODO_CALENDARIO_FECHAS CHECK (
        (TIPO_RECURRENCIA = 'MENSUAL' AND FECHA_INICIO IS NULL AND FECHA_FIN IS NULL)
        OR (TIPO_RECURRENCIA <> 'MENSUAL' AND FECHA_INICIO IS NOT NULL AND FECHA_FIN IS NOT NULL
            AND FECHA_INICIO <= FECHA_FIN))
);

COMMENT ON TABLE PERIODO_CALENDARIO IS 'CU-ADM-04: períodos LABORAL/NO_LABORAL de un calendario, con su recurrencia';
COMMENT ON COLUMN PERIODO_CALENDARIO.CODIGO IS 'Único dentro del calendario (RN15)';
COMMENT ON COLUMN PERIODO_CALENDARIO.FECHA_INICIO IS 'Inicio del rango de UNA_VEZ y SEMANAL; nulo en MENSUAL (RN11)';
COMMENT ON COLUMN PERIODO_CALENDARIO.FECHA_FIN IS 'Fin del rango de UNA_VEZ y SEMANAL; nulo en MENSUAL (RN11)';

CREATE INDEX IDX_PERIODO_CALENDARIO_CAL ON PERIODO_CALENDARIO (ID_CALENDARIO);

CREATE TABLE PERIODO_CALENDARIO_DIA_SEMANA (
    ID_PERIODO NUMBER(19)   NOT NULL,
    DIA_SEMANA VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_PERIODO_CAL_DIA_SEMANA PRIMARY KEY (ID_PERIODO, DIA_SEMANA),
    CONSTRAINT FK_PERIODO_CAL_DIA_SEMANA FOREIGN KEY (ID_PERIODO) REFERENCES PERIODO_CALENDARIO (ID_PERIODO),
    CONSTRAINT CK_PERIODO_CAL_DIA_SEMANA CHECK (DIA_SEMANA IN
        ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

COMMENT ON TABLE PERIODO_CALENDARIO_DIA_SEMANA IS 'CU-ADM-04: días de la semana de una recurrencia SEMANAL';

CREATE TABLE PERIODO_CALENDARIO_DIA_MES (
    ID_PERIODO NUMBER(19) NOT NULL,
    DIA_MES    NUMBER(2)  NOT NULL,
    CONSTRAINT PK_PERIODO_CAL_DIA_MES PRIMARY KEY (ID_PERIODO, DIA_MES),
    CONSTRAINT FK_PERIODO_CAL_DIA_MES FOREIGN KEY (ID_PERIODO) REFERENCES PERIODO_CALENDARIO (ID_PERIODO),
    CONSTRAINT CK_PERIODO_CAL_DIA_MES CHECK (DIA_MES BETWEEN 1 AND 31)
);

COMMENT ON TABLE PERIODO_CALENDARIO_DIA_MES IS 'CU-ADM-04: días del mes de una recurrencia MENSUAL';

CREATE TABLE PERIODO_CALENDARIO_MES (
    ID_PERIODO NUMBER(19)   NOT NULL,
    MES        VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_PERIODO_CAL_MES PRIMARY KEY (ID_PERIODO, MES),
    CONSTRAINT FK_PERIODO_CAL_MES FOREIGN KEY (ID_PERIODO) REFERENCES PERIODO_CALENDARIO (ID_PERIODO),
    CONSTRAINT CK_PERIODO_CAL_MES CHECK (MES IN ('JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE',
        'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER'))
);

COMMENT ON TABLE PERIODO_CALENDARIO_MES IS 'CU-ADM-04: meses de una recurrencia MENSUAL';

CREATE TABLE EXCEPCION_CALENDARIO (
    ID_EXCEPCION  NUMBER(19)    NOT NULL,
    ID_CALENDARIO NUMBER(19)    NOT NULL,
    FECHA         DATE          NOT NULL,
    TIPO          VARCHAR2(20)  NOT NULL,
    DESCRIPCION   VARCHAR2(500),
    CONSTRAINT PK_EXCEPCION_CALENDARIO PRIMARY KEY (ID_EXCEPCION),
    CONSTRAINT UK_EXCEPCION_CALENDARIO_FECHA UNIQUE (ID_CALENDARIO, FECHA),
    CONSTRAINT FK_EXCEPCION_CALENDARIO_CAL FOREIGN KEY (ID_CALENDARIO) REFERENCES CALENDARIO (ID_CALENDARIO),
    CONSTRAINT CK_EXCEPCION_CALENDARIO_TIPO CHECK (TIPO IN ('DIA_LABORAL', 'DIA_NO_LABORAL'))
);

COMMENT ON TABLE EXCEPCION_CALENDARIO IS 'CU-ADM-04: reclasificación puntual de una fecha, con prioridad sobre los períodos (RN01)';
