-- R001__rollback_tablas_catalogo.sql
-- Autor: equipo SIIP
-- Fecha: 2026-09-29
-- Descripción: revierte V001__crear_tablas_catalogo.sql (CU-ADM-01). Borra los datos.

DROP TABLE REGISTRO_VALOR;
DROP TABLE REGISTRO_CATALOGO;
DROP TABLE CAMPO_DEFINICION_VALOR_ENUM;
DROP TABLE CAMPO_DEFINICION;
DROP TABLE CATALOGO;

DROP SEQUENCE REGISTRO_CATALOGO_SEQ;
DROP SEQUENCE CAMPO_DEFINICION_SEQ;
DROP SEQUENCE CATALOGO_SEQ;
