-- R002__rollback_tablas_calendario.sql
-- Autor: equipo SIIP
-- Fecha: 2026-09-30
-- Descripción: revierte V002__crear_tablas_calendario.sql (CU-ADM-04). Borra los datos.

DROP TABLE EXCEPCION_CALENDARIO;
DROP TABLE PERIODO_CALENDARIO_MES;
DROP TABLE PERIODO_CALENDARIO_DIA_MES;
DROP TABLE PERIODO_CALENDARIO_DIA_SEMANA;
DROP TABLE PERIODO_CALENDARIO;
DROP TABLE CALENDARIO;

DROP SEQUENCE EXCEPCION_CALENDARIO_SEQ;
DROP SEQUENCE PERIODO_CALENDARIO_SEQ;
DROP SEQUENCE CALENDARIO_SEQ;
