--------------------------------------------------------------------------------
-- SIIP - Sistema de Información de Inversión Pública de El Salvador
-- Esquema Oracle - Catálogos transversales + Módulo Preinversión (M-01 a M-08)
-- Generado a partir de: WBS project_siip_v3.xlsx + use_cases-unificado.md
-- Compatibilidad: Oracle 12c+ (no usa BOOLEAN nativo, usa NUMBER(1))
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. CATÁLOGOS TRANSVERSALES
--------------------------------------------------------------------------------

CREATE SEQUENCE INSTITUCION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE INSTITUCION (
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    CODIGO              VARCHAR2(20)    NOT NULL,
    NOMBRE              VARCHAR2(250)   NOT NULL,
    MACROSECTOR         VARCHAR2(100),
    SECTOR_ACTIVIDAD    VARCHAR2(100),
    ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL,
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    FECHA_MODIFICACION  TIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    USUARIO_MODIFICACION VARCHAR2(100),
    CONSTRAINT PK_INSTITUCION PRIMARY KEY (ID_INSTITUCION),
    CONSTRAINT UK_INSTITUCION_CODIGO UNIQUE (CODIGO)
);
COMMENT ON TABLE INSTITUCION IS 'Catálogo de instituciones del Sector Público (clasificador institucional SIAF)';

CREATE SEQUENCE UNIDAD_EJECUTORA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE UNIDAD_EJECUTORA (
    ID_UNIDAD_EJECUTORA NUMBER(19)      NOT NULL,
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    CODIGO              VARCHAR2(20)    NOT NULL,
    NOMBRE              VARCHAR2(250)   NOT NULL,
    ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL,
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    FECHA_MODIFICACION  TIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    USUARIO_MODIFICACION VARCHAR2(100),
    CONSTRAINT PK_UNIDAD_EJECUTORA PRIMARY KEY (ID_UNIDAD_EJECUTORA),
    CONSTRAINT UK_UNIDAD_EJEC_CODIGO UNIQUE (CODIGO),
    CONSTRAINT FK_UE_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION)
);
COMMENT ON TABLE UNIDAD_EJECUTORA IS 'Unidad operativa ejecutora, subordinada a una Institución';

CREATE SEQUENCE USUARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE USUARIO (
    ID_USUARIO          NUMBER(19)      NOT NULL,
    NOMBRE_USUARIO      VARCHAR2(100)   NOT NULL,
    NOMBRE_COMPLETO     VARCHAR2(250)   NOT NULL,
    CORREO              VARCHAR2(250),
    ROL                 VARCHAR2(40)    NOT NULL,
    ID_UNIDAD_EJECUTORA NUMBER(19),
    ID_INSTITUCION      NUMBER(19),
    ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL,
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    FECHA_MODIFICACION  TIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    USUARIO_MODIFICACION VARCHAR2(100),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_USUARIO_NOMBRE UNIQUE (NOMBRE_USUARIO),
    CONSTRAINT FK_USUARIO_UE FOREIGN KEY (ID_UNIDAD_EJECUTORA) REFERENCES UNIDAD_EJECUTORA (ID_UNIDAD_EJECUTORA),
    CONSTRAINT FK_USUARIO_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    CONSTRAINT CK_USUARIO_ROL CHECK (ROL IN ('TECNICO_URP','TECNICO_PRE','COORDINADOR_PRE','VIABILIZADOR',
        'TECNICO_ASYMP','TECNICO_PROG','TECNICO_SEG','TECNICO_LEGAL','TECNICO_OPE','TECNICO_SIAF',
        'INGENIERO_DINAFI','COORDINADOR_PROGRAMACION','ADMINISTRADOR'))
);
COMMENT ON TABLE USUARIO IS 'Usuarios del sistema y su rol funcional (ver Anexo C de casos de uso)';

CREATE SEQUENCE DEPARTAMENTO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO     NUMBER(19)      NOT NULL,
    CODIGO              VARCHAR2(10)    NOT NULL,
    NOMBRE              VARCHAR2(100)   NOT NULL,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_DEPARTAMENTO),
    CONSTRAINT UK_DEPARTAMENTO_CODIGO UNIQUE (CODIGO)
);

CREATE SEQUENCE MUNICIPIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE MUNICIPIO (
    ID_MUNICIPIO        NUMBER(19)      NOT NULL,
    ID_DEPARTAMENTO     NUMBER(19)      NOT NULL,
    CODIGO              VARCHAR2(10)    NOT NULL,
    NOMBRE              VARCHAR2(100)   NOT NULL,
    CONSTRAINT PK_MUNICIPIO PRIMARY KEY (ID_MUNICIPIO),
    CONSTRAINT UK_MUNICIPIO_CODIGO UNIQUE (CODIGO),
    CONSTRAINT FK_MUNICIPIO_DEPTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

CREATE SEQUENCE FUENTE_FINANCIAMIENTO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE FUENTE_FINANCIAMIENTO (
    ID_FUENTE_FINANCIAMIENTO NUMBER(19) NOT NULL,
    CODIGO              VARCHAR2(20)    NOT NULL,
    NOMBRE              VARCHAR2(200)   NOT NULL,
    TIPO                VARCHAR2(40),
    ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_FUENTE_FINANCIAMIENTO PRIMARY KEY (ID_FUENTE_FINANCIAMIENTO),
    CONSTRAINT UK_FUENTE_FIN_CODIGO UNIQUE (CODIGO)
);
COMMENT ON TABLE FUENTE_FINANCIAMIENTO IS 'Catálogo de fuentes de financiamiento (propios, préstamo, donación, etc.)';

--------------------------------------------------------------------------------
-- 2. NÚCLEO DEL PROYECTO (PRE-01, PRE-01.5, PRE-02, PRE-03, PRE-3.5)
--------------------------------------------------------------------------------

CREATE SEQUENCE PROYECTO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PROYECTO (
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    CUP                 VARCHAR2(5),
    NOMBRE              VARCHAR2(300)   NOT NULL,
    INICIATIVA_INVERSION VARCHAR2(20)   NOT NULL,
    ID_UNIDAD_EJECUTORA NUMBER(19)      NOT NULL,
    ID_INSTITUCION      NUMBER(19)      NOT NULL,
    ESTADO              VARCHAR2(40)    NOT NULL,
    FECHA_INGRESO       TIMESTAMP       NOT NULL,
    FECHA_CUP_ASIGNADO  TIMESTAMP,
    ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL,
    MONTO_ESTIMADO_INVERSION NUMBER     NOT NULL,
    SECTOR              VARCHAR2(50)    NOT NULL,
    EJE_TEMATICO        VARCHAR2(50)    NOT NULL,
    ES_PROYECTO_EMERGENCIA NUMBER(1),
    TIPO_EVENTO         VARCHAR2(100),
    NUMERO_DECRETO_LEGISLATIVO VARCHAR2(50),
    EJE_PLAN_GOBIERNO   VARCHAR2(50),
    PLAN_SECTORIAL_REGIONAL VARCHAR2(50),
    DESCRIPCION_PROYECTO VARCHAR2(1000) NOT NULL,
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    FECHA_MODIFICACION  TIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    USUARIO_MODIFICACION VARCHAR2(100),
    CONSTRAINT PK_PROYECTO PRIMARY KEY (ID_PROYECTO),
    CONSTRAINT UK_PROYECTO_CUP UNIQUE (CUP),
    CONSTRAINT FK_PROYECTO_UE FOREIGN KEY (ID_UNIDAD_EJECUTORA) REFERENCES UNIDAD_EJECUTORA (ID_UNIDAD_EJECUTORA),
    CONSTRAINT FK_PROYECTO_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
    CONSTRAINT CK_PROYECTO_INICIATIVA CHECK (INICIATIVA_INVERSION IN ('PROGRAMA','PROYECTO','ESTUDIO_GENERAL')),
    CONSTRAINT CK_PROYECTO_ESTADO CHECK (ESTADO IN ('EN_REGISTRO','ENVIADO_DGICP_REGISTRO','OBSERVADO_DGICP_REGISTRO',
        'CUP_ASIGNADO','EN_FORMULACION','EN_VIABILIDAD','VIABLE','NO_VIABLE','ELEGIBLE','NO_ELEGIBLE',
        'PRIORIZADO','EN_BANCO_PROYECTOS','EN_EJECUCION','FINALIZADO','ARCHIVADO'))
);
COMMENT ON TABLE PROYECTO IS 'Entidad raíz: proyecto/programa/estudio de inversión pública. CU-PRE-01/01.5/02/03';

-- Campos de seleccion multiple de la pantalla "Nuevo registro" (CU-PRE-01): codigos de
-- Anexo C.1/C.1.5/C.2 seleccionados para el proyecto, sin FK contra MEDIDA_CATALOGO
-- (catalogo de referencia de esos mismos codigos, ver mas abajo en esta seccion).
CREATE TABLE PROYECTO_MEDIDA_GRD (
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    CODIGO              VARCHAR2(50)    NOT NULL,
    CONSTRAINT FK_PROYECTO_MEDIDA_GRD FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE PROYECTO_MEDIDA_GRD IS 'Categorias de GRD seleccionadas para el proyecto (Anexo C.1). CU-PRE-01';

CREATE TABLE PROYECTO_MEDIDA_GRC (
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    CODIGO              VARCHAR2(50)    NOT NULL,
    CONSTRAINT FK_PROYECTO_MEDIDA_GRC FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE PROYECTO_MEDIDA_GRC IS 'Categorias de GRC seleccionadas para el proyecto (Anexo C.1.5). CU-PRE-01';

CREATE TABLE PROYECTO_MEDIDA_ACC (
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    CODIGO              VARCHAR2(50)    NOT NULL,
    CONSTRAINT FK_PROYECTO_MEDIDA_ACC FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE PROYECTO_MEDIDA_ACC IS 'Categorias de ACC seleccionadas para el proyecto (Anexo C.2). CU-PRE-01';

CREATE SEQUENCE MEDIDA_CATALOGO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE MEDIDA_CATALOGO (
    ID_MEDIDA_CATALOGO  NUMBER(19)      NOT NULL,
    TIPO                VARCHAR2(10)    NOT NULL,
    CODIGO              VARCHAR2(50)    NOT NULL,
    DESCRIPCION         VARCHAR2(500)   NOT NULL,
    CONSTRAINT PK_MEDIDA_CATALOGO PRIMARY KEY (ID_MEDIDA_CATALOGO),
    CONSTRAINT CK_MEDIDA_CATALOGO_TIPO CHECK (TIPO IN ('GRD','GRC','ACC'))
);
COMMENT ON TABLE MEDIDA_CATALOGO IS 'Catalogo de referencia GRD/GRC/ACC (Anexos C.1, C.1.5, C.2), boton "Ver descripción de categorías". CU-PRE-01';

CREATE SEQUENCE ETAPA_PREINVERSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ETAPA_PREINVERSION (
    ID_ETAPA_PREINVERSION NUMBER(19)    NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    TIPO_ETAPA          VARCHAR2(30)    NOT NULL,
    FECHA_SELECCION     TIMESTAMP       NOT NULL,
    JUSTIFICACION       VARCHAR2(2000),
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    CONSTRAINT PK_ETAPA_PREINVERSION PRIMARY KEY (ID_ETAPA_PREINVERSION),
    CONSTRAINT FK_ETAPA_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_ETAPA_TIPO CHECK (TIPO_ETAPA IN ('PERFIL','PREFACTIBILIDAD','FACTIBILIDAD'))
);
COMMENT ON TABLE ETAPA_PREINVERSION IS 'Etapa de preinversión seleccionada para el proyecto. CU-PRE-3.5';

CREATE SEQUENCE SOLICITUD_PREINV_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE SOLICITUD_PREINVERSION (
    ID_SOLICITUD        NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    TIPO_SOLICITUD      VARCHAR2(20)    NOT NULL,
    ESTADO              VARCHAR2(30)    NOT NULL,
    FECHA_SOLICITUD     TIMESTAMP       NOT NULL,
    ID_TECNICO_ASIGNADO NUMBER(19),
    FECHA_ASIGNACION    TIMESTAMP,
    FECHA_ARCHIVO       TIMESTAMP,
    FECHA_ALERTA_ELIMINACION TIMESTAMP,
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    CONSTRAINT PK_SOLICITUD_PREINVERSION PRIMARY KEY (ID_SOLICITUD),
    CONSTRAINT FK_SOLICITUD_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_SOLICITUD_TECNICO FOREIGN KEY (ID_TECNICO_ASIGNADO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT CK_SOLICITUD_TIPO CHECK (TIPO_SOLICITUD IN ('CUP','OPINION_TECNICA')),
    CONSTRAINT CK_SOLICITUD_ESTADO CHECK (ESTADO IN ('REGISTRADA','ASIGNADA','EN_REVISION','OBSERVADA','APROBADA','ARCHIVADA'))
);
COMMENT ON TABLE SOLICITUD_PREINVERSION IS 'Solicitud de CUP u Opinión Técnica. CU-PRE-01, CU-PRE-01.5, CU-PRE-02';

CREATE SEQUENCE COMENTARIO_SOLICITUD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE COMENTARIO_SOLICITUD (
    ID_COMENTARIO       NUMBER(19)      NOT NULL,
    ID_SOLICITUD        NUMBER(19)      NOT NULL,
    ID_AUTOR            NUMBER(19)      NOT NULL,
    TEXTO               CLOB            NOT NULL,
    FECHA_COMENTARIO    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_COMENTARIO_SOLICITUD PRIMARY KEY (ID_COMENTARIO),
    CONSTRAINT FK_COMENTARIO_SOLICITUD FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD_PREINVERSION (ID_SOLICITUD),
    CONSTRAINT FK_COMENTARIO_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES USUARIO (ID_USUARIO)
);
COMMENT ON TABLE COMENTARIO_SOLICITUD IS 'Historial de comentarios de revisión sobre una solicitud. CU-PRE-01/01.5';

--------------------------------------------------------------------------------
-- 3. FORMULACIÓN DEL PERFIL (PRE-04 a PRE-09)
--------------------------------------------------------------------------------

CREATE SEQUENCE IDENTIFICACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE IDENTIFICACION (
    ID_IDENTIFICACION   NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    PROBLEMA_CENTRAL    VARCHAR2(2000)  NOT NULL,
    CAUSAS              CLOB,
    EFECTOS             CLOB,
    OBJETIVO_GENERAL    VARCHAR2(2000),
    ARCHIVO_ARBOL_PROBLEMAS VARCHAR2(500),
    ARCHIVO_ARBOL_OBJETIVOS VARCHAR2(500),
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    USUARIO_CREACION    VARCHAR2(100),
    FECHA_MODIFICACION  TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR2(100),
    CONSTRAINT PK_IDENTIFICACION PRIMARY KEY (ID_IDENTIFICACION),
    CONSTRAINT UK_IDENTIFICACION_PROYECTO UNIQUE (ID_PROYECTO),
    CONSTRAINT FK_IDENTIFICACION_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE IDENTIFICACION IS 'Identificación del problema y árbol de problemas/objetivos. CU-PRE-04';

CREATE SEQUENCE OBJETIVO_ESPECIFICO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE OBJETIVO_ESPECIFICO (
    ID_OBJETIVO_ESPECIFICO NUMBER(19)   NOT NULL,
    ID_IDENTIFICACION   NUMBER(19)      NOT NULL,
    DESCRIPCION         VARCHAR2(1000)  NOT NULL,
    ORDEN               NUMBER(3),
    CONSTRAINT PK_OBJETIVO_ESPECIFICO PRIMARY KEY (ID_OBJETIVO_ESPECIFICO),
    CONSTRAINT FK_OBJ_ESP_IDENTIFICACION FOREIGN KEY (ID_IDENTIFICACION) REFERENCES IDENTIFICACION (ID_IDENTIFICACION)
);

CREATE SEQUENCE ALTERNATIVA_SOLUCION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ALTERNATIVA_SOLUCION (
    ID_ALTERNATIVA_SOLUCION NUMBER(19)  NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    DESCRIPCION         VARCHAR2(2000)  NOT NULL,
    SELECCIONADA        NUMBER(1)       DEFAULT 0 NOT NULL,
    JUSTIFICACION       VARCHAR2(2000),
    CONSTRAINT PK_ALTERNATIVA_SOLUCION PRIMARY KEY (ID_ALTERNATIVA_SOLUCION),
    CONSTRAINT FK_ALT_SOLUCION_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE ALTERNATIVA_SOLUCION IS 'Alternativas de solución evaluadas. CU-PRE-05';

CREATE SEQUENCE INTERESADO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE INTERESADO (
    ID_INTERESADO       NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    NOMBRE              VARCHAR2(250)   NOT NULL,
    TIPO_INTERESADO     VARCHAR2(30)    NOT NULL,
    ROL_INTERES         VARCHAR2(500),
    POSICION            VARCHAR2(20)    NOT NULL,
    CONSTRAINT PK_INTERESADO PRIMARY KEY (ID_INTERESADO),
    CONSTRAINT FK_INTERESADO_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_INTERESADO_POSICION CHECK (POSICION IN ('A_FAVOR','EN_CONTRA','NEUTRAL'))
);
COMMENT ON TABLE INTERESADO IS 'Análisis de interesados del proyecto. CU-PRE-06';

CREATE SEQUENCE POBLACION_OBJETIVO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE POBLACION_OBJETIVO (
    ID_POBLACION_OBJETIVO NUMBER(19)    NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    POBLACION_REFERENCIA NUMBER(12),
    POBLACION_DEMANDANTE NUMBER(12),
    POBLACION_OBJETIVO  NUMBER(12),
    CRITERIOS_FOCALIZACION VARCHAR2(2000),
    CONSTRAINT PK_POBLACION_OBJETIVO PRIMARY KEY (ID_POBLACION_OBJETIVO),
    CONSTRAINT UK_POBLACION_OBJ_PROYECTO UNIQUE (ID_PROYECTO),
    CONSTRAINT FK_POBLACION_OBJ_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE POBLACION_OBJETIVO IS 'Población de referencia, demandante y objetivo. CU-PRE-07';

CREATE SEQUENCE AREA_INFLUENCIA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE AREA_INFLUENCIA (
    ID_AREA_INFLUENCIA  NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ID_DEPARTAMENTO     NUMBER(19)      NOT NULL,
    ID_MUNICIPIO        NUMBER(19)      NOT NULL,
    DESCRIPCION         VARCHAR2(1000),
    CONSTRAINT PK_AREA_INFLUENCIA PRIMARY KEY (ID_AREA_INFLUENCIA),
    CONSTRAINT FK_AREA_INFL_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_AREA_INFL_DEPTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO),
    CONSTRAINT FK_AREA_INFL_MUNICIPIO FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_MUNICIPIO)
);
COMMENT ON TABLE AREA_INFLUENCIA IS 'Área geográfica de influencia del proyecto (1:N). CU-PRE-08';

CREATE SEQUENCE ANALISIS_MERCADO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ANALISIS_MERCADO (
    ID_ANALISIS_MERCADO NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    DEMANDA             CLOB,
    OFERTA              CLOB,
    BRECHA              CLOB,
    METODOLOGIA         VARCHAR2(2000),
    CONSTRAINT PK_ANALISIS_MERCADO PRIMARY KEY (ID_ANALISIS_MERCADO),
    CONSTRAINT UK_ANALISIS_MERCADO_PROYECTO UNIQUE (ID_PROYECTO),
    CONSTRAINT FK_ANALISIS_MERCADO_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE ANALISIS_MERCADO IS 'Análisis de oferta, demanda y brecha. CU-PRE-09';

--------------------------------------------------------------------------------
-- 4. ESTUDIOS TÉCNICO, AMBIENTAL, RIESGO Y LEGAL (PRE-11, 12, 14, 15, 16)
--------------------------------------------------------------------------------

CREATE SEQUENCE DESCRIPCION_TECNICA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE DESCRIPCION_TECNICA (
    ID_DESCRIPCION_TECNICA NUMBER(19)   NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    DESCRIPCION         CLOB            NOT NULL,
    ESPECIFICACIONES    CLOB,
    VIDA_UTIL_ANIOS     NUMBER(4),
    CONSTRAINT PK_DESCRIPCION_TECNICA PRIMARY KEY (ID_DESCRIPCION_TECNICA),
    CONSTRAINT UK_DESC_TECNICA_PROYECTO UNIQUE (ID_PROYECTO),
    CONSTRAINT FK_DESC_TECNICA_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE DESCRIPCION_TECNICA IS 'Descripción técnica del proyecto. CU-PRE-11';

CREATE SEQUENCE LOCALIZACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE LOCALIZACION (
    ID_LOCALIZACION     NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ID_DEPARTAMENTO     NUMBER(19)      NOT NULL,
    ID_MUNICIPIO        NUMBER(19)      NOT NULL,
    DIRECCION           VARCHAR2(500),
    LATITUD             NUMBER(10,7),
    LONGITUD            NUMBER(10,7),
    CONSTRAINT PK_LOCALIZACION PRIMARY KEY (ID_LOCALIZACION),
    CONSTRAINT FK_LOCALIZACION_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_LOCALIZACION_DEPTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO),
    CONSTRAINT FK_LOCALIZACION_MUNICIPIO FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_MUNICIPIO)
);
COMMENT ON TABLE LOCALIZACION IS 'Localización geográfica exacta del proyecto (1:N). CU-PRE-12';

CREATE SEQUENCE ANALISIS_AMBIENTAL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ANALISIS_AMBIENTAL (
    ID_ANALISIS_AMBIENTAL NUMBER(19)    NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    CATEGORIA_AMBIENTAL VARCHAR2(20)    NOT NULL,
    PERMISOS_REQUERIDOS VARCHAR2(2000),
    OBSERVACIONES       VARCHAR2(2000),
    CONSTRAINT PK_ANALISIS_AMBIENTAL PRIMARY KEY (ID_ANALISIS_AMBIENTAL),
    CONSTRAINT UK_ANALISIS_AMB_PROYECTO UNIQUE (ID_PROYECTO),
    CONSTRAINT FK_ANALISIS_AMB_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_ANALISIS_AMB_CATEGORIA CHECK (CATEGORIA_AMBIENTAL IN ('I','II','III','NO_APLICA'))
);
COMMENT ON TABLE ANALISIS_AMBIENTAL IS 'Análisis ambiental y permisos requeridos. CU-PRE-14';

CREATE SEQUENCE ANALISIS_RIESGO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ANALISIS_RIESGO (
    ID_ANALISIS_RIESGO  NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    TIPO_RIESGO         VARCHAR2(100)   NOT NULL,
    NIVEL_RIESGO        VARCHAR2(20)    NOT NULL,
    MEDIDAS_MITIGACION  VARCHAR2(2000),
    CONSTRAINT PK_ANALISIS_RIESGO PRIMARY KEY (ID_ANALISIS_RIESGO),
    CONSTRAINT FK_ANALISIS_RIESGO_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_ANALISIS_RIESGO_NIVEL CHECK (NIVEL_RIESGO IN ('BAJO','MEDIO','ALTO'))
);
COMMENT ON TABLE ANALISIS_RIESGO IS 'Análisis de riesgo del proyecto (1:N, un registro por tipo de riesgo). CU-PRE-15';

CREATE SEQUENCE ANALISIS_LEGAL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ANALISIS_LEGAL (
    ID_ANALISIS_LEGAL   NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    MARCO_LEGAL_APLICABLE VARCHAR2(2000),
    OBSERVACIONES       VARCHAR2(2000),
    CONSTRAINT PK_ANALISIS_LEGAL PRIMARY KEY (ID_ANALISIS_LEGAL),
    CONSTRAINT UK_ANALISIS_LEGAL_PROYECTO UNIQUE (ID_PROYECTO),
    CONSTRAINT FK_ANALISIS_LEGAL_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE ANALISIS_LEGAL IS 'Análisis legal del proyecto. CU-PRE-16';

--------------------------------------------------------------------------------
-- 5. PRESUPUESTO Y COSTOS (PRE-17, PRE-18)
--------------------------------------------------------------------------------

CREATE SEQUENCE COMPONENTE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE COMPONENTE (
    ID_COMPONENTE       NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    NOMBRE              VARCHAR2(250)   NOT NULL,
    DESCRIPCION         VARCHAR2(1000),
    CONSTRAINT PK_COMPONENTE PRIMARY KEY (ID_COMPONENTE),
    CONSTRAINT FK_COMPONENTE_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE COMPONENTE IS 'Componente/rubro en que se desglosa el proyecto. CU-PRE-17';

CREATE SEQUENCE PRESUPUESTO_INVERSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PRESUPUESTO_INVERSION (
    ID_PRESUPUESTO_INVERSION NUMBER(19) NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ID_COMPONENTE        NUMBER(19)     NOT NULL,
    ID_FUENTE_FINANCIAMIENTO NUMBER(19) NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    MONTO               NUMBER(18,2)    NOT NULL,
    CONSTRAINT PK_PRESUPUESTO_INVERSION PRIMARY KEY (ID_PRESUPUESTO_INVERSION),
    CONSTRAINT FK_PRES_INV_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_PRES_INV_COMPONENTE FOREIGN KEY (ID_COMPONENTE) REFERENCES COMPONENTE (ID_COMPONENTE),
    CONSTRAINT FK_PRES_INV_FUENTE FOREIGN KEY (ID_FUENTE_FINANCIAMIENTO) REFERENCES FUENTE_FINANCIAMIENTO (ID_FUENTE_FINANCIAMIENTO)
);
COMMENT ON TABLE PRESUPUESTO_INVERSION IS 'Presupuesto de inversión por componente/fuente/año. CU-PRE-17';

CREATE SEQUENCE FLUJO_COSTO_OM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE FLUJO_COSTO_OM (
    ID_FLUJO_COSTO_OM   NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    MONTO_OPERACION     NUMBER(18,2)    DEFAULT 0 NOT NULL,
    MONTO_MANTENIMIENTO NUMBER(18,2)    DEFAULT 0 NOT NULL,
    VALOR_RESCATE       NUMBER(18,2),
    CONSTRAINT PK_FLUJO_COSTO_OM PRIMARY KEY (ID_FLUJO_COSTO_OM),
    CONSTRAINT FK_FLUJO_COSTO_OM_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT UK_FLUJO_COSTO_OM_ANIO UNIQUE (ID_PROYECTO, ANIO)
);
COMMENT ON TABLE FLUJO_COSTO_OM IS 'Flujo de costos de Operación y Mantenimiento por año. CU-PRE-18';

--------------------------------------------------------------------------------
-- 6. EVALUACIÓN SOCIOECONÓMICA Y FINANCIERA (PRE-20, 21, 21.5, 22.1, 23)
--------------------------------------------------------------------------------

CREATE SEQUENCE FLUJO_BENEFICIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE FLUJO_BENEFICIO (
    ID_FLUJO_BENEFICIO  NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    TIPO_BENEFICIO      VARCHAR2(100)   NOT NULL,
    MONTO               NUMBER(18,2)    NOT NULL,
    CONSTRAINT PK_FLUJO_BENEFICIO PRIMARY KEY (ID_FLUJO_BENEFICIO),
    CONSTRAINT FK_FLUJO_BENEFICIO_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);
COMMENT ON TABLE FLUJO_BENEFICIO IS 'Flujo de beneficios del proyecto por año. CU-PRE-20';

CREATE SEQUENCE FLUJO_CAJA_INDICADOR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE FLUJO_CAJA_INDICADOR (
    ID_FLUJO_CAJA_INDICADOR NUMBER(19)  NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    INGRESOS            NUMBER(18,2)    DEFAULT 0 NOT NULL,
    EGRESOS             NUMBER(18,2)    DEFAULT 0 NOT NULL,
    FLUJO_NETO          NUMBER(18,2)    NOT NULL,
    CONSTRAINT PK_FLUJO_CAJA_INDICADOR PRIMARY KEY (ID_FLUJO_CAJA_INDICADOR),
    CONSTRAINT FK_FLUJO_CAJA_IND_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT UK_FLUJO_CAJA_IND_ANIO UNIQUE (ID_PROYECTO, ANIO)
);
COMMENT ON TABLE FLUJO_CAJA_INDICADOR IS 'Flujo de caja económico usado para el cálculo de indicadores. CU-PRE-21';

CREATE SEQUENCE FLUJO_CAJA_FINANCIERO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE FLUJO_CAJA_FINANCIERO (
    ID_FLUJO_CAJA_FINANCIERO NUMBER(19) NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    INGRESOS_FINANCIEROS NUMBER(18,2)   DEFAULT 0 NOT NULL,
    EGRESOS_FINANCIEROS NUMBER(18,2)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_FLUJO_CAJA_FINANCIERO PRIMARY KEY (ID_FLUJO_CAJA_FINANCIERO),
    CONSTRAINT FK_FLUJO_CAJA_FIN_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT UK_FLUJO_CAJA_FIN_ANIO UNIQUE (ID_PROYECTO, ANIO)
);
COMMENT ON TABLE FLUJO_CAJA_FINANCIERO IS 'Flujo de caja financiero del proyecto. CU-PRE-21.5';

CREATE SEQUENCE PROG_FIN_PREINV_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PROGRAMACION_FIN_PREINVERSION (
    ID_PROGRAMACION_FIN_PREINV NUMBER(19) NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    CUATRIMESTRE        NUMBER(1)       NOT NULL,
    MONTO_PROGRAMADO    NUMBER(18,2)    NOT NULL,
    CONSTRAINT PK_PROG_FIN_PREINVERSION PRIMARY KEY (ID_PROGRAMACION_FIN_PREINV),
    CONSTRAINT FK_PROG_FIN_PREINV_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_PROG_FIN_PREINV_CUATRI CHECK (CUATRIMESTRE IN (1,2,3))
);
COMMENT ON TABLE PROGRAMACION_FIN_PREINVERSION IS 'Programación financiera cuatrimestral de la preinversión. CU-PRE-22.1';

CREATE SEQUENCE INDICADOR_EVALUACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE INDICADOR_EVALUACION (
    ID_INDICADOR_EVALUACION NUMBER(19)  NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    TIPO_INDICADOR       VARCHAR2(30)   NOT NULL,
    VALOR               NUMBER(18,4)    NOT NULL,
    FECHA_CALCULO       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_INDICADOR_EVALUACION PRIMARY KEY (ID_INDICADOR_EVALUACION),
    CONSTRAINT FK_INDICADOR_EVAL_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_INDICADOR_EVAL_TIPO CHECK (TIPO_INDICADOR IN ('VAN','TIR','VAN_SOCIAL','TIR_SOCIAL','RELACION_BENEFICIO_COSTO'))
);
COMMENT ON TABLE INDICADOR_EVALUACION IS 'Indicadores de evaluación socioeconómica/financiera. CU-PRE-21, CU-PRE-23';

--------------------------------------------------------------------------------
-- 7. VIABILIDAD, ELEGIBILIDAD, OPINIÓN TÉCNICA Y PRIORIZACIÓN (PRE-24 a 26.5)
--------------------------------------------------------------------------------

CREATE SEQUENCE VIABILIDAD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE VIABILIDAD (
    ID_VIABILIDAD       NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    RESULTADO           VARCHAR2(20)    NOT NULL,
    FECHA_EVALUACION    TIMESTAMP       NOT NULL,
    OBSERVACIONES       VARCHAR2(2000),
    ID_EVALUADOR        NUMBER(19)      NOT NULL,
    CONSTRAINT PK_VIABILIDAD PRIMARY KEY (ID_VIABILIDAD),
    CONSTRAINT FK_VIABILIDAD_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_VIABILIDAD_EVALUADOR FOREIGN KEY (ID_EVALUADOR) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT CK_VIABILIDAD_RESULTADO CHECK (RESULTADO IN ('VIABLE','NO_VIABLE','OBSERVADO'))
);
COMMENT ON TABLE VIABILIDAD IS 'Resultado de la evaluación de viabilidad. CU-PRE-24';

CREATE SEQUENCE ELEGIBILIDAD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ELEGIBILIDAD (
    ID_ELEGIBILIDAD     NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    RESULTADO           VARCHAR2(20)    NOT NULL,
    CRITERIOS_CUMPLIDOS VARCHAR2(2000),
    FECHA_EVALUACION    TIMESTAMP       NOT NULL,
    CONSTRAINT PK_ELEGIBILIDAD PRIMARY KEY (ID_ELEGIBILIDAD),
    CONSTRAINT FK_ELEGIBILIDAD_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_ELEGIBILIDAD_RESULTADO CHECK (RESULTADO IN ('ELEGIBLE','NO_ELEGIBLE'))
);
COMMENT ON TABLE ELEGIBILIDAD IS 'Resultado de la evaluación de elegibilidad. CU-PRE-25';

CREATE SEQUENCE OPINION_TECNICA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE OPINION_TECNICA (
    ID_OPINION_TECNICA  NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    RESULTADO           VARCHAR2(20)    NOT NULL,
    FECHA_EMISION       TIMESTAMP       NOT NULL,
    OBSERVACIONES       VARCHAR2(2000),
    ID_TECNICO_RESPONSABLE NUMBER(19)   NOT NULL,
    CONSTRAINT PK_OPINION_TECNICA PRIMARY KEY (ID_OPINION_TECNICA),
    CONSTRAINT FK_OPINION_TEC_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_OPINION_TEC_TECNICO FOREIGN KEY (ID_TECNICO_RESPONSABLE) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT CK_OPINION_TEC_RESULTADO CHECK (RESULTADO IN ('FAVORABLE','DESFAVORABLE','OBSERVADO'))
);
COMMENT ON TABLE OPINION_TECNICA IS 'Opinión técnica emitida sobre el proyecto. CU-PRE-26';

CREATE SEQUENCE PRIORIZACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PRIORIZACION (
    ID_PRIORIZACION     NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    CUATRIMESTRE        NUMBER(1)       NOT NULL,
    PUNTAJE             NUMBER(8,2)     NOT NULL,
    POSICION_RANKING    NUMBER(6),
    FECHA_PRIORIZACION  TIMESTAMP       NOT NULL,
    CONSTRAINT PK_PRIORIZACION PRIMARY KEY (ID_PRIORIZACION),
    CONSTRAINT FK_PRIORIZACION_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT CK_PRIORIZACION_CUATRI CHECK (CUATRIMESTRE IN (1,2,3))
);
COMMENT ON TABLE PRIORIZACION IS 'Priorización cuatrimestral del proyecto dentro del banco. CU-PRE-26.5';

-- Nota: "Banco de Proyectos" (CU-PRE-29) no genera tabla propia: es una consulta/vista
-- sobre PROYECTO filtrando ESTADO IN ('VIABLE','ELEGIBLE','PRIORIZADO'). [SUPUESTO - validar]
CREATE OR REPLACE VIEW VW_BANCO_PROYECTOS AS
SELECT p.*
FROM PROYECTO p
WHERE p.ESTADO IN ('VIABLE', 'ELEGIBLE', 'PRIORIZADO', 'EN_BANCO_PROYECTOS');
COMMENT ON TABLE VW_BANCO_PROYECTOS IS 'Vista del Banco de Proyectos. CU-PRE-29 [SUPUESTO: sin tabla propia]';

--------------------------------------------------------------------------------
-- 8. PROGRAMACIÓN Y AVANCE CUATRIMESTRAL DE PREINVERSIÓN - PAP (PRE-30 a 33)
--------------------------------------------------------------------------------

CREATE SEQUENCE PROG_CUATRI_FIN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PROG_CUATRIMESTRAL_FINANCIERA (
    ID_PROG_CUATRI_FIN  NUMBER(19)      NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    CUATRIMESTRE        NUMBER(1)       NOT NULL,
    MONTO_PROGRAMADO    NUMBER(18,2)    NOT NULL,
    CONSTRAINT PK_PROG_CUATRI_FIN PRIMARY KEY (ID_PROG_CUATRI_FIN),
    CONSTRAINT FK_PROG_CUATRI_FIN_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT UK_PROG_CUATRI_FIN UNIQUE (ID_PROYECTO, ANIO, CUATRIMESTRE),
    CONSTRAINT CK_PROG_CUATRI_FIN_CUATRI CHECK (CUATRIMESTRE IN (1,2,3))
);
COMMENT ON TABLE PROG_CUATRIMESTRAL_FINANCIERA IS 'Programación cuatrimestral financiera de la preinversión (PAP). CU-PRE-30';

CREATE SEQUENCE PROG_CUATRI_META_FIS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PROG_CUATRIMESTRAL_META_FISICA (
    ID_PROG_CUATRI_META_FIS NUMBER(19)  NOT NULL,
    ID_PROYECTO         NUMBER(19)      NOT NULL,
    ANIO                NUMBER(4)       NOT NULL,
    CUATRIMESTRE        NUMBER(1)       NOT NULL,
    META_FISICA_PROGRAMADA NUMBER(18,2) NOT NULL,
    UNIDAD_MEDIDA       VARCHAR2(50)    NOT NULL,
    CONSTRAINT PK_PROG_CUATRI_META_FIS PRIMARY KEY (ID_PROG_CUATRI_META_FIS),
    CONSTRAINT FK_PROG_CUATRI_META_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT UK_PROG_CUATRI_META_FIS UNIQUE (ID_PROYECTO, ANIO, CUATRIMESTRE),
    CONSTRAINT CK_PROG_CUATRI_META_CUATRI CHECK (CUATRIMESTRE IN (1,2,3))
);
COMMENT ON TABLE PROG_CUATRIMESTRAL_META_FISICA IS 'Programación cuatrimestral de metas físicas de la preinversión (PAP). CU-PRE-31';

CREATE SEQUENCE AVANCE_FIN_CUATRI_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE AVANCE_FINANCIERO_CUATRIMESTRAL (
    ID_AVANCE_FIN_CUATRI NUMBER(19)     NOT NULL,
    ID_PROG_CUATRI_FIN  NUMBER(19)      NOT NULL,
    MONTO_EJECUTADO     NUMBER(18,2)    NOT NULL,
    PORCENTAJE_AVANCE   NUMBER(5,2)     NOT NULL,
    FECHA_REGISTRO      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AVANCE_FIN_CUATRI PRIMARY KEY (ID_AVANCE_FIN_CUATRI),
    CONSTRAINT FK_AVANCE_FIN_CUATRI_PROG FOREIGN KEY (ID_PROG_CUATRI_FIN) REFERENCES PROG_CUATRIMESTRAL_FINANCIERA (ID_PROG_CUATRI_FIN)
);
COMMENT ON TABLE AVANCE_FINANCIERO_CUATRIMESTRAL IS 'Avance financiero cuatrimestral del PAP. CU-PRE-32';

CREATE SEQUENCE AVANCE_META_FIS_CUATRI_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE AVANCE_CUATRI_META_FISICA (
    ID_AVANCE_META_FIS_CUATRI NUMBER(19) NOT NULL,
    ID_PROG_CUATRI_META_FIS NUMBER(19)  NOT NULL,
    AVANCE_FISICO        NUMBER(18,2)   NOT NULL,
    PORCENTAJE_AVANCE     NUMBER(5,2)   NOT NULL,
    FECHA_REGISTRO        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AVANCE_META_FIS_CUATRI PRIMARY KEY (ID_AVANCE_META_FIS_CUATRI),
    CONSTRAINT FK_AVANCE_META_FIS_PROG FOREIGN KEY (ID_PROG_CUATRI_META_FIS) REFERENCES PROG_CUATRIMESTRAL_META_FISICA (ID_PROG_CUATRI_META_FIS)
);
COMMENT ON TABLE AVANCE_CUATRI_META_FISICA IS 'Avance cuatrimestral por metas físicas del PAP. CU-PRE-33';

--------------------------------------------------------------------------------
-- FIN DEL SCRIPT - Módulo Preinversión
--------------------------------------------------------------------------------
