import type { ContenidoIniciativaResumen } from '../../../api/generated/administracion-catalogos';

/**
 * El "Anexo F" tal como lo devuelve el servidor, copiado de la respuesta real de
 * GET /catalogos/contenido-iniciativas-proyecto el 30/09/2026. Las pruebas lo
 * usan para no inventar una matriz que luego no coincida con la de producción.
 *
 * Son 26 filas y el anexo en Excel tiene 30: al catálogo del servidor le faltan
 * "Situación Base Optimizada" (CU-PRE-10), "Tamaño" (CU-PRE-13) y las dos de
 * Programación de Inversión (CU-PRE-22.2 y 22.4). Se deja igual que el servidor,
 * con la falta incluida, porque es lo que el frontend recibe hoy.
 */
export const ANEXO_F: ContenidoIniciativaResumen[] = [
  { contenido: 'Antecedentes', ubicacionCasoUso: 'CUPRE-04', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'SIN_DATO' },
  { contenido: 'Problema Central', ubicacionCasoUso: 'CUPRE-04', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'SIN_DATO' },
  { contenido: 'Objetivo General', ubicacionCasoUso: 'CUPRE-04', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'SIN_DATO' },
  { contenido: 'Objetivos Específicos', ubicacionCasoUso: 'CUPRE-04', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'SIN_DATO' },
  { contenido: 'Análisis de Alternativas de Solución', ubicacionCasoUso: 'CUPRE-05', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: false, aplicaDiseno: false, aplicaPrograma: false, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'SIN_DATO' },
  { contenido: 'Análisis de Interesados', ubicacionCasoUso: 'CUPRE-06', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: false, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Análisis de la Población', ubicacionCasoUso: 'CUPRE-07', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Área de Influencia', ubicacionCasoUso: 'CUPRE-08', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: false, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Análisis de Mercado', ubicacionCasoUso: 'CUPRE-09', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: false, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Descripción Técnica', ubicacionCasoUso: 'CUPRE-11', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Localización', ubicacionCasoUso: 'CUPRE-12', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Análisis Ambiental', ubicacionCasoUso: 'CUPRE-14', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: false, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Análisis de Riesgos', ubicacionCasoUso: 'CUPRE-15', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Análisis Legal', ubicacionCasoUso: 'CUPRE-16', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: false, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Presupuesto de Inversión', ubicacionCasoUso: 'CUPRE-17', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Fuentes de Financiamiento', ubicacionCasoUso: 'CUPRE-17', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Presupuesto de O&M', ubicacionCasoUso: 'CUPRE-18', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Productos del Proyecto', ubicacionCasoUso: 'CUPRE-23', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Flujo de Beneficios', ubicacionCasoUso: 'CUPRE-20', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: false, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Flujo de Caja e Indicadores', ubicacionCasoUso: 'CUPRE-21', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: false, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Programación Financiera Preinversión', ubicacionCasoUso: 'CUPRE-22.1', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: false, aplicaPrograma: false, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'NO_APLICA_AL_CU' },
  { contenido: 'Programación Física Preinversión', ubicacionCasoUso: 'CUPRE-22.3', aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: false, aplicaPrograma: false, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'NO_APLICA_AL_CU' },
  { contenido: 'Nota de solicitud de OT', ubicacionCasoUso: null, aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Documento de Preinversión', ubicacionCasoUso: null, aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Otros documentos', ubicacionCasoUso: null, aplicaPerfil: true, aplicaPrefactibilidad: true,
    aplicaFactibilidad: true, aplicaDiseno: true, aplicaPrograma: true, aplicaEstudioGeneral: true,
    aplicaActualizacionOt: 'APLICA' },
  { contenido: 'Marco Lógico', ubicacionCasoUso: null, aplicaPerfil: false, aplicaPrefactibilidad: false,
    aplicaFactibilidad: false, aplicaDiseno: false, aplicaPrograma: true, aplicaEstudioGeneral: false,
    aplicaActualizacionOt: 'SIN_DATO' },
];
