schemaVersion: 2.2.0
metadata:
  name: dgicp-siip-admin-srv-java-springboot
  displayName: dgicp-siip-admin-srv-java-springboot
  description: Java application using Spring Boot and OpenJDK 21
  icon: https://spring.io/images/spring-logo-9146a4d3298760c2e7e49595184e1975.svg
  tags:
    - Java
    - Spring Boot
  projectType: Spring Boot
  language: Java
  version: 1.5.0
  website: https://spring.io
starterProjects:
  - name: spring-initializr
    zip:
      location: https://start.spring.io/starter.zip?type=maven-project&language=java&bootVersion=3.5.16&baseDir=demo&groupId=sv.gob.mh&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=sv.gob.mh.demo&packaging=jar&javaVersion=21&dependencies=web,data-jpa,validation,security,oauth2-resource-server,actuator
components:
  - name: tools
    container:
      image: registry.access.redhat.com/ubi8/openjdk-21:1.20-3.1721207868
      args: ['tail', '-f', '/dev/null']
      memoryLimit: 1024Mi ## default app nowhere needs this but leaving room for expansion.
      mountSources: true
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      endpoints:
        - name: https-springboot
          targetPort: 8080
          protocol: https
        - exposure: none
          name: debug
          targetPort: 5858
      env:
        - name: DEBUG_PORT
          value: '5858'
  - name: m2
    volume:
      size: 3Gi
commands:
  - id: init-compile
    exec:
      component: tools
      commandLine: './mvnw -Dmaven.repo.local=/home/user/.m2/repository compile'
      workingDir: ${PROJECT_SOURCE}
  - id: dev-run
    exec:
      component: tools
      commandLine: './mvnw -Dmaven.repo.local=/home/user/.m2/repository spring-boot:run'
      hotReloadCapable: true
      group:
        kind: run
        isDefault: true
      workingDir: ${PROJECT_SOURCE}
  - id: dev-debug
    exec:
      component: tools
      commandLine: './mvnw -Dmaven.repo.local=/home/user/.m2/repository spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"'
      hotReloadCapable: true
      group:
        kind: debug
        isDefault: true
      workingDir: ${PROJECT_SOURCE}
events:
  postStart:
    - init-compile