{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend-ui.fullname" . }}-cmp
  labels:
    {{- include "frontend-ui.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
